import {characterVoices} from './character-voices.js?v=1';
import {playShot} from './shot-sound.js';
import {playReload,noirMusic} from './fps-audio.js?v=1';
import {generateSector} from './fps-sector.js?v=1';
const PI=Math.PI, TAU=PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const TITLES={circle:['01','КРУГОВОЙ ПОИСК'],front:['02','ЧИСТЫЙ ПЕРЕНОС'],third:['03','ПЛЕЧО НАПАРНИКА'],bandage:['04','КРАСНЫЙ КОРИДОР'],magazine:['05','ПОСЛЕДНИЙ МАГАЗИН'],moving:['06','ПОДВИЖНЫЙ РУБЕЖ'],judgement:['07','НЕ СТРЕЛЯЙ В ТЕНЬ']};
function layout(combat){
 const n=17,m=Array.from({length:n},(_,y)=>Array.from({length:n},(_,x)=>x===0||y===0||x===n-1||y===n-1?1:0));
 if(combat){for(let y=1;y<16;y++){if(![4,11].includes(y))m[y][7]=1;if(![7,13].includes(y))m[y][12]=1;}for(let x=1;x<16;x++)if(![3,9,14].includes(x))m[9][x]=1;for(const [x,y] of [[4,6],[5,6],[9,3],[10,12],[14,10]])m[y][x]=2;}
 else for(const [x,y] of [[2,2],[14,2],[2,14],[14,14]])m[y][x]=2;
 return m;
}
function solid(s,x,y){return (s.map[Math.floor(y)]?.[Math.floor(x)]??1)!==0;}
function sight(s,a,b){let d=Math.hypot(b.x-a.x,b.y-a.y);for(let t=.08;t<d-.08;t+=.07)if(solid(s,a.x+(b.x-a.x)*t/d,a.y+(b.y-a.y)*t/d))return false;return true;}
function cover(s){return !s.entities.some(e=>e.kind==='enemy'&&e.hp>0&&sight(s,s,e));}
function tone(ctx,f,t,d,vol,type='sine'){const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.035);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+d+.01);}
function texture(kind){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d');x.fillStyle=kind===2?'#635442':'#2b4149';x.fillRect(0,0,64,64);for(let y=0;y<64;y++){for(let i=0;i<64;i++){const r=(i*31+y*17+i*y)%13;x.fillStyle=kind===2?`rgba(220,170,112,${r/160})`:`rgba(158,186,176,${r/200})`;x.fillRect(i,y,1,1);}}
 if(kind===2){x.fillStyle='#281f1b';x.fillRect(0,0,64,5);x.fillRect(0,59,64,5);x.fillRect(4,0,5,64);x.fillRect(55,0,5,64);x.strokeStyle='#a88356';x.lineWidth=4;x.beginPath();x.moveTo(8,8);x.lineTo(56,56);x.moveTo(56,8);x.lineTo(8,56);x.stroke();}
 else{for(let y=0;y<64;y+=16){x.fillStyle='#152a31';x.fillRect(0,y,64,2);for(let i=(y%32?0:16);i<64;i+=32)x.fillRect(i,y,2,16);}x.fillStyle='#91a48b';x.fillRect(0,46,64,3);x.fillStyle='#dfb662';x.fillRect(0,49,64,2);}
 return c;
}
function sprite(kind){const c=document.createElement('canvas');c.width=48;c.height=80;const x=c.getContext('2d');x.imageSmoothingEnabled=false;
 if(kind==='target'){x.fillStyle='#353731';x.fillRect(7,4,34,58);x.fillStyle='#ccbb92';x.fillRect(9,6,30,54);x.fillStyle='#4b4338';x.fillRect(21,11,7,8);x.fillRect(16,19,18,29);x.fillStyle='#c99765';x.fillRect(20,23,10,15);x.strokeStyle='#ebe1bd';x.strokeRect(18,22,14,18);x.fillStyle='#28383c';x.fillRect(21,61,5,18);x.fillRect(12,76,23,3);}
 else if(kind==='exit'){x.fillStyle='#deb578';x.fillRect(1,1,46,78);x.fillStyle='#182a29';x.fillRect(5,10,38,70);x.fillStyle='#5b8072';x.fillRect(9,13,30,63);x.fillStyle='#e9cea0';x.fillRect(34,48,3,4);x.fillStyle='#e4ddb1';x.fillRect(6,2,36,6);}
 else{const enemy=kind==='enemy',civilian=kind==='civilian';x.fillStyle='#0b151a';x.fillRect(10,16,28,46);x.fillStyle=enemy?'#85493d':civilian?'#b3a482':'#3f7688';x.fillRect(12,21,24,34);x.fillStyle=enemy?'#b5664a':'#548b9a';x.fillRect(14,22,20,4);x.fillStyle='#c8a582';x.fillRect(17,6,15,14);x.fillStyle='#202b2e';x.fillRect(15,4,19,6);x.fillRect(17,11,15,4);x.fillStyle=enemy?'#dfaa73':'#ddc274';x.fillRect(23,27,4,5);x.fillStyle='#131f26';x.fillRect(14,53,8,26);x.fillRect(27,53,8,26);x.fillRect(4,29,9,9);x.fillRect(35,29,8,11);x.fillStyle='#85928d';if(!civilian){x.fillRect(8,32,31,4);x.fillStyle='#222c30';x.fillRect(20,34,7,17);}else{x.fillStyle='#d9b38a';x.fillRect(5,13,7,20);x.fillRect(36,13,7,20);}}
 return c;
}
export function mountFPS(host,{exercise='circle',tutorial=false,seed=0,officers=99,flashlightBinding='KeyF',onExit=()=>{},onFinish=()=>{}}={}){
 const combat=['bandage','magazine'].includes(exercise);if(combat&&flashlightBinding==='KeyF')flashlightBinding='KeyL';const title=TITLES[exercise]||TITLES.circle;
 const root=document.createElement('section');root.className='fps2';root.innerHTML=`<canvas id="fpsCanvas" width="640" height="360" tabindex="0"></canvas><div class="fps2-top"><div><small>LSPD / NIGHT SCHOOL</small><strong>${title[0]} — ${title[1]}${tutorial?' / УЧЕБНАЯ ПЛОЩАДКА':''}</strong></div><span id="fpsClock"></span><span id="fpsCompass"></span><div class="fps2-buttons"><button id="fpsMusic">♫ Музыка: выкл.</button><input id="fpsVolume" aria-label="Громкость музыки" type="range" min="0" max="100" value="55"><button id="fpsExit">В меню</button></div></div><div class="fps2-reticle" id="fpsReticle" hidden>+</div><div id="fpsWarning" class="fps2-warning" hidden></div><form id="fpsAmmoQuestion" hidden><label>Сколько у вас сейчас патронов?<input id="fpsAmmoAnswer" type="number" min="0" max="30" required></label><button>Ответить</button></form><div id="fpsPartner" class="fps2-partner"></div><canvas id="fpsGrouping" width="130" height="100"></canvas><div class="fps2-message" id="fpsMessage"></div><div class="fps2-hud"><div id="fpsObjective"></div><div id="fpsWeapon"></div><div id="fpsScore"></div></div><div class="fps2-keys">WASD ходьба · мышь взгляд · ЛКМ огонь · ПКМ прицел · Space ствол · Q/E наклон · R магазин · Shift красться · ${combat?'F бинт · ':''}Фонарик ${flashlightBinding} · Esc пауза</div><div id="fpsInspect" hidden><small>ОСМОТР МАГАЗИНА</small><div class="fps2-mag"><div id="fpsFill"></div></div><span id="fpsEstimate"></span></div><div class="fps2-pause" id="fpsPause"><div><small>LOS SUEÑOS · INTERNAL TRAINING</small><h1>${title[1]}</h1><p id="fpsBrief"></p><label>Чувствительность мыши <input id="fpsSensitivity" type="range" min="0.2" max="3" step="0.05"><output id="fpsSensitivityValue"></output></label><label><input id="fpsVoice" type="checkbox"> Два голоса: Альварес и напарница</label><button id="fpsStart">НАЧАТЬ СМЕНУ</button><button id="fpsRetry">ПОВТОРИТЬ СЕКТОР / ПАРУ</button><p>Мышь захватывается для обзора. Esc — пауза и доступ к меню.</p></div></div>`;host.replaceChildren(root);
 const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),ui=id=>root.querySelector('#'+id),keys=new Set(),abort=new AbortController(),opts={signal:abort.signal},audio=noirMusic();
 const s={exercise,seed,map:layout(combat),x:combat?3.5:8.5,y:combat?4.5:8.5,yaw:0,pitch:0,raised:true,ads:false,lean:null,light:false,ammo:combat?12:30,reserve:combat?2:90,reload:0,bandaging:0,bandageSafe:false,wounded:false,health:100,damageHits:0,bleed:0,question:null,elapsed:0,active:false,done:false,entities:[],shots:0,hitsCount:0,destroyed:0,misses:0,resign:0,killed:0,orderErrors:0,completed:0,series:0,points:0,grouping:0,mistakes:0,streak:0,wave:0,round:1,expectedSide:'left',hits:[[],[]],transferCrossed:false,inspect:false,inspectedBeforeContact:false,sectorShots:0,recoil:0,flash:0,hitFlash:0,woundFlash:0,tracer:0,step:0,sensitivity:clamp(Number(localStorage.getItem('lspd-sensitivity'))||1,.2,3),inspecting:false,impacts:[],intermission:0,feedback:'',feedbackTime:0,tutorialStep:0};
 const texts=combat?(exercise==='bandage'?'Пройдите коридор к освещённой двери. Противники предупреждают об атаке и открывают огонь. После ранения скройтесь за стеной и нажмите F. Двигаться при перевязке можно, стрелять нельзя.':'Оцените магазин удержанием R до первого контакта. Короткое R меняет магазин; после замены осмотрите снова. Подавите угрозы и выйдите через освещённую дверь.'):'По три попадания на мишень. Свой на пути ствола — сначала Space, затем перенос. '+(exercise==='front'?'Работайте слева направо.':exercise==='third'?'Левая тройка: Q, опущенный ствол, ПКМ и свет. Затем безопасный перенос, E и правая тройка. После правой тройки новая пара появится автоматически. Безопасный перенос между мишенями обязателен.':'Ищите новые пары во всех секторах. Свой может стоять между целями или сбоку; иногда его нет.');
 ui('fpsBrief').textContent=texts;const textures=[null,texture(1),texture(2)],sprites={target:sprite('target'),enemy:sprite('enemy'),ally:sprite('ally'),exit:sprite('exit'),civilian:sprite('civilian')};let last=performance.now(),raf=0,rStart=null,hold=null,zbuffer=new Float32Array(640),hintAt=0;
 const voices=characterVoices(ui('fpsPartner'));
 function note(t){s.feedback=t;s.feedbackTime=3.8;voices.say(t,ui('fpsVoice').checked&&s.active);}
 ui('fpsVoice').checked=localStorage.getItem('lspd-voice')!=='off';ui('fpsVoice').onchange=e=>{localStorage.setItem('lspd-voice',e.target.checked?'on':'off');if(!e.target.checked)voices.stop();};ui('fpsSensitivity').value=s.sensitivity;ui('fpsSensitivityValue').textContent=s.sensitivity.toFixed(2);ui('fpsSensitivity').oninput=e=>{s.sensitivity=Number(e.target.value);localStorage.setItem('lspd-sensitivity',s.sensitivity);ui('fpsSensitivityValue').textContent=s.sensitivity.toFixed(2);};
 function pair(){clearTimeout(hold);rStart=null;s.inspecting=false;ui('fpsInspect').hidden=true;s.wave++;s.lastGroup=s.hits.flat();if(s.lastGroup.length&&exercise!=='third'){let spread=0;for(const a of s.lastGroup)for(const b of s.lastGroup)spread=Math.max(spread,Math.hypot(a.x-b.x,a.y-b.y));s.grouping+=Math.max(0,Math.round(80-spread*100));}s.intermission=0;s.hits=[[],[]];s.transferCrossed=false;s.expectedSide='left';
  if(combat){Object.assign(s,generateSector(seed*100+s.round*7+s.wave));s.yaw=0;s.pitch=0;s.health=100;s.wounded=false;s.damageHits=0;s.bleed=0;s.bandaging=0;s.reload=0;s.inspect=false;s.inspecting=false;s.question=null;s.inspectedBeforeContact=false;s.sectorShots=0;s.ammo=exercise==='magazine'?[3,12,5][s.round-1]:12;s.reserve=2;s.raised=true;note('Новый лабиринт. Враги скрыты за углами. F — перевязка, фонарик '+flashlightBinding);return;}
  if(exercise==='judgement'){s.map=layout(false);for(let y=1;y<16;y++)if(![6,7,8,9,10].includes(y))s.map[y][10]=1;s.x=8.5;s.y=8.5;s.yaw=0;s.raised=true;s.ads=false;s.scan=new Set();s.scanDwell={};s.roomEntered=false;s.decisionClock=0;const scheme=(s.wave-1)%3,y=6.5+(s.wave%3)*2;s.entities=scheme===1?[{kind:'civilian',x:13.5,y,hp:1}]:scheme===2?[{kind:'civilian',x:12.5,y,hp:1},{kind:'enemy',x:13.5,y:y+.85,hp:1,clock:999}]:[{kind:'enemy',x:13.5,y,hp:1,clock:999}];s.entities.forEach(e=>e.rise=0);note('Обзор 3 секторов: слева, центр, справа. Отступите от стены на 1–2 шага. Просматривайте комнату снаружи: двигайтесь вдоль проёма, не входите до проверки трёх секторов. Мирного не трогайте, у заложника ищите открытый силуэт врага.');return;}
  const third=exercise==='third';let base=exercise==='circle'?(s.wave*1.71+.45)%TAU:0;
  s.entities=[{kind:'target',side:'left',x:8.5+Math.cos(base-.35)*5.7,y:8.5+Math.sin(base-.35)*5.7,hp:3},{kind:'target',side:'right',x:8.5+Math.cos(base+.35)*5.7,y:8.5+Math.sin(base+.35)*5.7,hp:3}];
  const scheme=third?0:(s.wave-1)%3;if(scheme!==1)s.entities.push({kind:'ally',x:8.5+Math.cos(base+(scheme===2?-.95:0))*3.5,y:8.5+Math.sin(base+(scheme===2?-.95:0))*3.5,hp:1});
  if(exercise==='moving'){s.entities=s.entities.filter(e=>e.kind==='target');s.entities.forEach((e,i)=>{e.baseY=e.y;e.baseX=e.x;e.phase=i*PI;e.moving=true;});}
  if(third){s.x=8.5;s.y=8.5;s.yaw=-.35;s.pitch=0;s.raised=true;s.light=false;s.lean=null;s.ads=false;}
  if(s.entities.some(e=>e.kind==='ally'&&Math.abs(wrap(Math.atan2(e.y-s.y,e.x-s.x)-s.yaw))<.15)){s.raised=true;s.ads=false;}
  note(exercise==='circle'?'Новая пара: '+['впереди','справа','сзади','слева'][Math.floor(((wrap(base-s.yaw)+TAU)%TAU+PI/4)%(TAU)/(PI/2))]+'. Проверьте путь ствола.':third?'Левая тройка: выгляните Q, опустите ствол, прицел и свет.':'Новая пара. Сначала левая тройка.');
 }
 function dispose(){if(s.done)return;s.done=true;abort.abort();keys.clear();clearTimeout(hold);cancelAnimationFrame(raf);audio.stop();voices.dispose();if(document.pointerLockElement===canvas)document.exitPointerLock();}
 function finish(reason){if(s.done)return;if(reason==='shot_dead'||reason==='bleed_out'){s.mistakes++;s.streak=0;}const result={reason,duration:s.elapsed,destroyed:s.destroyed,resign:s.resign,killed:s.killed,points:s.points,series:s.series,grouping:s.grouping,completed:s.completed,mistakes:s.mistakes,streak:s.streak,orderErrors:s.orderErrors,shots:s.shots,hitCount:s.hitsCount,misses:s.misses};dispose();if(tutorial)onExit();else onFinish(result);}
 function damage(){s.damageHits++;s.health=Math.max(0,100-s.damageHits*34);if(!s.wounded)s.bleed=11;s.wounded=true;s.woundFlash=.8;note('РАНЕНИЕ '+s.damageHits+'/3. До кровопотери '+s.bleed.toFixed(1)+' с — укрытие и F.');if(s.damageHits>=3)finish('shot_dead');}
 function askAmmo(e){note('Сколько патронов осталось в магазине?');s.question={enemy:e,actual:s.ammo};s.ads=false;s.inspecting=false;ui('fpsInspect').hidden=true;rStart=null;clearTimeout(hold);keys.clear();document.exitPointerLock?.();ui('fpsAmmoQuestion').hidden=false;ui('fpsAmmoAnswer').value='';ui('fpsAmmoAnswer').focus();}
 ui('fpsAmmoQuestion').onsubmit=e=>{e.preventDefault();if(!s.question)return;const q=s.question,n=Number(ui('fpsAmmoAnswer').value);if(!Number.isInteger(n))return;s.question=null;q.enemy.hidden=false;ui('fpsAmmoQuestion').hidden=true;if(Math.abs(n-q.actual)>2)damage();else note('Оценка верна. Контакт.');if(!s.done){s.active=true;ui('fpsPause').hidden=true;canvas.focus();canvas.requestPointerLock?.()?.catch(()=>{});}};
 function pause(){if(s.done)return;voices.stop();if(document.pointerLockElement===canvas)document.exitPointerLock();s.active=false;s.ads=false;s.inspecting=false;ui('fpsInspect').hidden=true;keys.clear();rStart=null;clearTimeout(hold);ui('fpsPause').hidden=false;ui('fpsStart').textContent='ПРОДОЛЖИТЬ';}
 ui('fpsRetry').onclick=()=>{s.mistakes++;pair();if(!combat&&tutorial){s.tutorialStep=0;s.x=8.5;s.y=8.5;s.raised=true;}note('Повтор. Ошибка отмечена, предыдущие успехи сохранены.');};ui('fpsExit').onclick=()=>{dispose();onExit();};ui('fpsStart').onclick=()=>{s.active=true;last=performance.now();ui('fpsPause').hidden=true;canvas.focus();canvas.requestPointerLock?.()?.catch(()=>note('Захват мыши недоступен. Кликните в сцену или используйте мышь в окне.'));};
 ui('fpsMusic').onclick=async()=>{const b=ui('fpsMusic');b.disabled=true;try{const on=await audio.toggle();b.textContent=on?'♫ Музыка: вкл.':'♫ Музыка: выкл.';b.dataset.audioState=on?'running':'closed';}catch(e){b.textContent='♫ Звук недоступен';note(e.message);}finally{b.disabled=false;}};ui('fpsVolume').oninput=e=>audio.set(Number(e.target.value)/100);
 document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==canvas&&!s.question)pause();},opts);window.addEventListener('blur',pause,opts);
 function inspect(){if(s.reload||s.bandaging)return;s.inspect=true;s.inspecting=true;s.ads=false;s.inspectedBeforeContact ||= s.sectorShots===0;ui('fpsInspect').hidden=false;ui('fpsFill').style.height=Math.round(s.ammo/(combat?12:30)*100)+'%';ui('fpsEstimate').textContent=s.ammo===0?'ПУСТО':s.ammo<(combat?5:10)?'МАЛО':s.ammo<(combat?9:23)?'ОКОЛО ПОЛОВИНЫ':'БОЛЬШЕ ПОЛОВИНЫ';note('Оцените заполненность. Замена — короткое R.');}
 function reload(){if(s.reload||s.bandaging)return;if(s.reserve<=0){note('Запас исчерпан.');return;}s.reload=1.5;playReload();s.ads=false;ui('fpsInspect').hidden=true;note('Смена магазина. Огонь недоступен до завершения.');}
 if(combat&&flashlightBinding==='KeyF')flashlightBinding='KeyL';
 function bindLight(code){return code===flashlightBinding&&!(combat&&code==='KeyF');}
 window.addEventListener('keydown',e=>{if(e.code==='Escape'){pause();return;}if(!s.active||s.done||s.question)return;if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','KeyR','KeyF','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;
  if(bindLight(e.code)){s.light=!s.light;note(s.light?'Фонарик включён.':'Фонарик выключен.');completeThird();return;}
  if(e.code==='Enter'&&flashlightBinding==='Mouse0'){fire();return;}if(['ShiftLeft','ShiftRight'].includes(e.code)&&flashlightBinding==='Mouse2'){if(!s.raised&&!s.reload&&!s.bandaging)s.ads=true;return;}if(e.code==='Space'){s.raised=!s.raised;s.ads=false;note(s.raised?'Ствол вверх — безопасный перенос.':'Оружие готово.');completeThird();}
  if(['KeyQ','KeyE'].includes(e.code)){const side=e.code==='KeyQ'?'left':'right';s.lean=s.lean===side?null:side;s.ads=false;completeThird();}
  if(e.code==='KeyR'&&rStart===null){rStart=performance.now();hold=setTimeout(()=>{if(rStart!==null&&s.active)inspect();},550);}
  if(e.code==='KeyF'&&combat){if(!s.wounded){note('Раны нет. Бинт не требуется.');return;}if(!s.bandaging){if(!cover(s)){ui('fpsWarning').textContent='ВЫ НЕ МОЖЕТЕ ПЕРЕВЯЗАТЬСЯ ВНЕ УКРЫТИЯ';s.warning=3;note('ВЫ НЕ МОЖЕТЕ ПЕРЕВЯЗАТЬСЯ ВНЕ УКРЫТИЯ');return;}s.bandaging=3.1;s.bandageSafe=true;s.ads=false;note(s.bandageSafe?'Перевязка: оставайтесь за укрытием.':'Открытая линия огня. Перевязка здесь не засчитается.');}}
 },opts);
 window.addEventListener('keyup',e=>{keys.delete(e.code);if(s.question)return;if(['ShiftLeft','ShiftRight'].includes(e.code)&&flashlightBinding==='Mouse2')s.ads=false;if(e.code==='KeyR'&&rStart!==null){const held=performance.now()-rStart;clearTimeout(hold);rStart=null;if(s.active){if(held<550)reload();else {inspect();s.inspecting=false;ui('fpsInspect').hidden=true;}}}},opts);
 const bearing=e=>wrap(Math.atan2(e.y-s.y,e.x-s.x)-s.yaw);
 function unsafe(oldYaw,newYaw){if(s.raised)return;for(const a of s.entities)if(a.kind==='ally'&&a.hp>0){const b=Math.atan2(a.y-s.y,a.x-s.x),turn=wrap(newYaw-oldYaw);for(let i=0,n=Math.max(1,Math.ceil(Math.abs(turn)/.02));i<=n;i++)if(Math.abs(wrap(b-oldYaw-turn*i/n))<.065){s.resign++;a.hp=0;s.mistakes++;note('Опасный перенос: напарник отказался работать. Сначала поднимайте ствол.');if(exercise==='third'){s.hits=[[],[]];s.raised=true;s.lean=null;s.ads=false;s.light=false;s.transferCrossed=false;s.entities.filter(e=>e.kind==='target').forEach(e=>e.hp=3);}return;}}}
 canvas.addEventListener('mousemove',e=>{if(!s.active||s.question)return;const old=s.yaw;s.yaw+=e.movementX*.0023*s.sensitivity*(s.ads?.55:1);s.pitch=clamp(s.pitch-e.movementY*.0018*s.sensitivity,-.4,.4);unsafe(old,s.yaw);if(exercise==='third'&&s.hits[0].length===3&&s.raised){const a=s.entities.find(e=>e.kind==='ally');if(a&&Math.sign(wrap(Math.atan2(a.y-s.y,a.x-s.x)-old))!==Math.sign(bearing(a)))s.transferCrossed=true;}},opts);
 canvas.addEventListener('contextmenu',e=>e.preventDefault(),opts);canvas.addEventListener('mousedown',e=>{if(!s.active)return;e.preventDefault();if(flashlightBinding===`Mouse${e.button}`){s.light=!s.light;completeThird();return;}if(e.button===2){if(!s.raised&&!s.reload&&!s.bandaging)s.ads=true;else note('Опустите ствол пробелом перед прицеливанием.');}if(e.button===0)fire();},opts);window.addEventListener('mouseup',e=>{if(e.button===2)s.ads=false;},opts);
 function eye(){const lean=(s.lean==='left'?-.17:s.lean==='right'?.17:0);return {x:s.x-Math.sin(s.yaw)*lean,y:s.y+Math.cos(s.yaw)*lean};}
 function projection(e){const cam=eye(),dx=e.x-cam.x,dy=e.y-cam.y,d=Math.hypot(dx,dy),a=wrap(Math.atan2(dy,dx)-s.yaw),depth=d*Math.cos(a),f=s.ads?530:360;if(depth<=.08||Math.abs(a)>1.2)return null;return {x:320+Math.tan(a)*f,y:180+s.pitch*360,k:f/depth,d:depth};}
 function fire(){if(s.question||s.intermission||s.inspecting||s.raised||s.reload||s.bandaging||!s.ammo){note(s.intermission?'Новая пара через секунду.':s.inspecting?'Осмотр: отпустите R для огня.':s.raised?'Ствол поднят. Space — вернуть оружие.':s.bandaging?'Перевязка: стрелять нельзя.':s.reload?'Дождитесь магазина.':'Пустой магазин — короткое R.');return;}
  s.ammo--;s.shots++;s.sectorShots++;s.flash=.12;s.tracer=.16;playShot();const ax=s.ads?320:390,ay=s.ads?180:222;s.tracerPoint={x:ax,y:ay};let chosen=null,best=Infinity;
  for(const e of s.entities){if(e.hp<=0||e.hidden||(e.rise!==undefined&&e.rise<.9)||e.kind==='exit')continue;const p=projection(e);if(!p||!sight(s,eye(),e))continue;const width=e.kind==='target'?.58:.62,height=e.kind==='target'?.98:1.25;if(Math.abs(p.x-ax)<p.k*width/2&&Math.abs(p.y-ay)<p.k*height/2&&p.d<best){chosen=e;best=p.d;}}
  if(chosen?.kind==='civilian'){chosen.hp=0;s.mistakes++;s.recoil=2.4;s.pitch=clamp(s.pitch+.045,-.4,.4);finish('civilian_hit');return;}
  if(chosen?.kind==='ally'){chosen.hp=0;s.killed++;s.mistakes++;note('Попадание в напарника. Безопасность важнее скорости.');if(exercise==='third'){s.hits=[[],[]];s.raised=true;s.entities.filter(e=>e.kind==='target').forEach(e=>e.hp=3);}}
  else if(chosen){const side=chosen.side==='right'?1:0;if(exercise==='front'&&chosen.side!==s.expectedSide){s.orderErrors++;note('Порядок нарушен: сейчас '+(s.expectedSide==='left'?'левая':'правая')+' тройка.');}
   else if(exercise==='third'&&(!s.ads||!s.light||s.lean!==(side?'right':'left')||(side===1&&!s.transferCrossed)||(side===0&&s.hits[0].length===3))){note('Нужны правильный наклон, прицел, свет и безопасный перенос.');}
   else{chosen.hp--;s.hitsCount++;s.hitFlash=.18;s.points+=15;{const p=projection(chosen);chosen.marks ||= [];const mark={x:(ax-p.x)/p.k,y:(ay-p.y)/p.k};chosen.marks.push(mark);s.impacts.push({...mark,entity:chosen});s.hits[side].push({x:(p.x-ax)/p.k,y:(p.y-ay)/p.k});}if(!chosen.hp){chosen.fall=.8;s.destroyed++;s.points+=70;if(exercise==='front')s.expectedSide=chosen.side==='left'?'right':'left';note(chosen.kind==='enemy'?'Угроза подавлена.':'Тройка готова.');}else note('Попадание '+(3-chosen.hp)+'/3. Корректируйте отдачу.');}
  }else{s.misses++;note('Промах. Патрон потрачен; попадания остаются.');}
  s.recoil=2.4;s.pitch=clamp(s.pitch+.045,-.4,.4);
  if(!combat&&exercise!=='third'&&exercise!=='judgement'&&s.entities.filter(e=>e.kind==='target').every(e=>!e.hp))s.intermission=1.25;
 }
 function completeThird(){if(s.intermission||exercise!=='third'||s.hits[1].length!==3)return;s.series++;s.completed++;let spread=0;for(const hits of s.hits)for(const a of hits)for(const b of hits)spread=Math.max(spread,Math.hypot(a.x-b.x,a.y-b.y));const bonus=Math.max(0,Math.round(80-spread*100));s.grouping+=bonus;s.points+=100+bonus;s.intermission=1.25;note('Серия завершена. Баллы за кучность: '+bonus);}
 const lessons=['Двигайтесь WASD: сделайте несколько шагов.','Space: опустите поднятый ствол.','Удерживайте ПКМ и попадите в учебную мишень.','Короткое R: дождитесь завершения замены магазина.','Space: поднимите ствол и безопасно переведите взгляд.','Обучение завершено. Выйдите в меню и выберите смену.'];
 function tutorialProgress(){if(!tutorial)return;const t=s.tutorialStep;if(t===0&&Math.hypot(s.x-8.5,s.y-8.5)>.3)s.tutorialStep=1;else if(t===1&&!s.raised)s.tutorialStep=2;else if(t===2&&s.hitsCount>0&&s.ads)s.tutorialStep=3;else if(t===3&&s.tutorialReloaded)s.tutorialStep=4;else if(t===4&&s.raised&&Math.abs(s.yaw-s.tutorialYaw)>.3)s.tutorialStep=5;s.feedback=lessons[s.tutorialStep];s.feedbackTime=1;}
 function update(dt){if(s.question)return;
  for(const e of s.entities)if(e.fall)e.fall=Math.max(0,e.fall-dt);if(exercise==='moving')for(const e of s.entities)if(e.moving){const y=e.baseY+Math.sin(s.elapsed*1.5+e.phase)*1.25;if(!solid(s,e.baseX,y))e.y=y;}
  if(exercise==='judgement'){for(const e of s.entities)e.rise=Math.min(1,(e.rise||0)+dt*2);for(const e of s.entities)if(e.hp>0&&sight(s,eye(),e)&&Math.abs(bearing(e))<.5){s.decisionClock+=dt;}for(const y of [5.5,8.5,11.5]){const v={x:14.5,y};if(s.x<10&&Math.abs(s.y-(y===5.5?7.7:y===11.5?9.3:8.5))<.4&&sight(s,eye(),v)&&Math.abs(bearing(v))<.15){s.scanDwell[y]=(s.scanDwell[y]||0)+dt;if(s.scanDwell[y]>=.08)s.scan.add(y);}}if(s.x>10&&!s.roomEntered){s.roomEntered=true;if(s.scan.size<3){s.scan.clear();s.mistakes++;note('Вход до обзора: вернитесь к проёму и открывайте обзор постепенно.');}}if(s.entities.every(e=>e.kind!=='enemy'||!e.hp)&&s.scan.size>=3&&!s.intermission){s.completed++;s.points+=100;s.intermission=1.25;note('Решение принято: мирные не пострадали.');}}if(!tutorial)s.elapsed+=dt;s.step+=dt;const f=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),r=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),n=Math.hypot(f,r)||1,sp=(keys.has('ShiftLeft')||keys.has('ShiftRight')?.65:s.wounded?1.35:s.ads?1.45:2.4)*dt;
  const dx=(Math.cos(s.yaw)*f-Math.sin(s.yaw)*r)/n*sp,dy=(Math.sin(s.yaw)*f+Math.cos(s.yaw)*r)/n*sp;
  for(const [axis,d] of [['x',dx],['y',dy]]){const x=s.x+(axis==='x'?d:0),y=s.y+(axis==='y'?d:0);if(![[x-.18,y-.18],[x+.18,y-.18],[x-.18,y+.18],[x+.18,y+.18]].some(([a,b])=>solid(s,a,b)))s[axis]+=d;}
  if(s.reload){s.reload=Math.max(0,s.reload-dt);if(!s.reload){if(combat){s.reserve--;s.ammo=12;}else{const n=Math.min(30-s.ammo,s.reserve);s.ammo+=n;s.reserve-=n;}playReload(true);s.tutorialReloaded=true;s.tutorialYaw=s.yaw;s.inspect=false;ui('fpsInspect').hidden=true;note('Магазин установлен.'+(exercise==='magazine'?' Осмотрите заново.':''));}}
  if(s.bandaging){if(!cover(s)){s.bandaging=0;s.warning=3;ui('fpsWarning').textContent='ВЫ НЕ МОЖЕТЕ ПЕРЕВЯЗАТЬСЯ ВНЕ УКРЫТИЯ';}s.bandageSafe&&=cover(s);s.bandaging=Math.max(0,s.bandaging-dt);if(!s.bandaging){if(s.bandageSafe){s.wounded=false;s.bleed=0;note('Рана закрыта. Продолжайте движение.');}else{s.mistakes++;note('Перевязка прервана линией огня. Найдите укрытие.');}}}
  for(const e of s.entities)if(combat&&e.kind==='enemy'&&e.hp>0){if(e.hidden&&sight(s,s,e)&&Math.hypot(e.x-s.x,e.y-s.y)<7){if(exercise==='magazine'&&!e.asked){e.asked=true;askAmmo(e);return;}e.hidden=false;}if(e.hidden)continue;e.clock-=dt;if(e.clock<=0){e.clock=2.8;if(sight(s,s,e)){e.flash=.18;playShot();damage();if(s.done)return;}}}if(s.wounded){s.bleed-=dt;if(s.bleed<=0){finish('bleed_out');return;}}
  if(combat){const exit=s.entities.find(e=>e.kind==='exit');if(exit&&Math.hypot(exit.x-s.x,exit.y-s.y)<.8){const remaining=s.entities.some(e=>e.kind==='enemy'&&e.hp>0);if(exercise==='bandage'&&s.wounded)note('Сначала закройте рану в укрытии.');else if(exercise==='magazine'&&(!s.inspect||!s.inspectedBeforeContact||remaining))note(remaining?'Остались активные угрозы.':!s.inspect?'Осмотрите магазин после замены.':'Осмотр должен быть до первого контакта.');else{s.completed++;s.streak++;s.points+=180;s.round++;if(s.round>3){finish('extracted');return;}pair();}}}
  if(exercise==='third')completeThird();if(s.intermission){s.intermission=Math.max(0,s.intermission-dt);if(!s.intermission)pair();}
  for(const k of ['flash','hitFlash','woundFlash','feedbackTime','tracer'])s[k]=Math.max(0,s[k]-dt);s.recoil*=Math.exp(-dt*7);if(!s.raised&&exercise!=='third')unsafe(s.yaw,s.yaw);tutorialProgress();
  if(!tutorial&&(s.elapsed>=(combat?240:90)||(!s.ammo&&!s.reserve)||officers-s.resign-s.killed<=0))finish(s.elapsed>=(combat?240:90)?'time_limit':officers-s.resign-s.killed<=0?'no_officers':'ammo_depleted');
 }
 function draw(now){ui('fpsWarning').hidden=!(s.warning>0);if(s.active)s.warning=Math.max(0,(s.warning||0)-.016);const w=640,h=360,f=s.ads?530:360,cam=eye(),horizon=180+s.pitch*360;ctx.imageSmoothingEnabled=false;const sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#080f18');sky.addColorStop(1,'#263b43');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle='#23343a';ctx.fillRect(0,horizon,w,h-horizon);
  for(let y=Math.max(1,Math.ceil(horizon));y<h;y+=3){const depth=f*.5/Math.max(1,y-horizon),shade=clamp(.6-depth*.02,.13,.6);ctx.fillStyle=`rgb(${Math.round(36*shade)},${Math.round(57*shade)},${Math.round(63*shade)})`;ctx.fillRect(0,y,w,3);for(let x=0;x<w;x+=4){const a=s.yaw+Math.atan((x-320)/f),d=depth/Math.cos(a-s.yaw),fx=cam.x+Math.cos(a)*d,fy=cam.y+Math.sin(a)*d;if((Math.floor(fx*2)+Math.floor(fy*2))%2===0){ctx.fillStyle=`rgba(151,169,158,${shade*.12})`;ctx.fillRect(x,y,4,3);}}}
  for(let x=0;x<w;x++){const angle=s.yaw+Math.atan((x-320)/f),rx=Math.cos(angle),ry=Math.sin(angle);let mx=Math.floor(cam.x),my=Math.floor(cam.y);const ddx=Math.abs(1/rx),ddy=Math.abs(1/ry),sx=rx<0?-1:1,sy=ry<0?-1:1;let ax=(rx<0?cam.x-mx:mx+1-cam.x)*ddx,ay=(ry<0?cam.y-my:my+1-cam.y)*ddy,side=0,steps=0;while(steps++<50){if(ax<ay){ax+=ddx;mx+=sx;side=0;}else{ay+=ddy;my+=sy;side=1;}if((s.map[my]?.[mx]??1)!==0)break;}
   const distance=side?ay-ddy:ax-ddx,depth=Math.max(.05,distance*Math.cos(angle-s.yaw)),size=f/depth,top=horizon-size/2;zbuffer[x]=depth;const wallX=side?cam.x+distance*rx:cam.y+distance*ry,u=Math.floor((wallX-Math.floor(wallX))*64),kind=s.map[my]?.[mx]===2?2:1;ctx.drawImage(textures[kind],u,0,1,64,x,top,1,size);const torch=s.light?clamp(1-Math.abs(x-320)/210,0,1)*clamp(1-depth/18,0,1):0;ctx.fillStyle=`rgba(2,10,16,${clamp(.12+depth*.042+(side?.1:0)-torch*.9,.03,.85)})`;ctx.fillRect(x,top,1,size);if(torch>0){ctx.fillStyle=`rgba(255,231,164,${torch*.55})`;ctx.fillRect(x,top,1,size);}if((mx+my)%5===0&&kind===1){ctx.fillStyle=`rgba(236,182,95,${clamp(.22-depth*.015,0,.2)})`;ctx.fillRect(x,top,1,size*.23);}}
  const visible=s.entities.filter(e=>(e.hp>0||e.fall>0)&&!e.hidden).map(e=>({e,p:projection(e)})).filter(v=>v.p).sort((a,b)=>b.p.d-a.p.d);
  for(const {e,p} of visible){const rise=e.hp<=0?Math.max(0,e.fall/.8):(e.rise===undefined?1:e.rise);const sh=p.k*(e.kind==='target'?1.05:1.35),sw=sh*.6,left=p.x-sw/2,top=p.y-sh/2+sh*(1-rise);const img=sprites[e.kind];for(let x=Math.max(0,Math.floor(left));x<Math.min(w,left+sw);x++){if(p.d>zbuffer[x]+.02)continue;const u=clamp(Math.floor((x-left)/sw*48),0,47);ctx.drawImage(img,u,0,1,80,x,top,1,sh);}
   for(const m of e.marks||[]){const mx=p.x+m.x*p.k,my=p.y+m.y*p.k;if(mx>=0&&mx<640&&p.d<zbuffer[Math.floor(mx)]+.1){ctx.fillStyle='#130c05';ctx.beginPath();ctx.arc(mx,my,Math.max(2,p.k*.025),0,TAU);ctx.fill();ctx.strokeStyle='#ffcb6b';ctx.stroke();}}
   if(Math.abs(p.x-320)<280&&p.d<8){ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.fillStyle=e.kind==='ally'?'#90d2dc':e.kind==='enemy'?'#ffb580':'#e9d19c';const label=e.kind==='civilian'?'МИРНЫЙ · НЕ СТРЕЛЯТЬ':e.kind==='ally'?'СВОЙ · НЕ СТРЕЛЯТЬ':e.kind==='enemy'?(e.clock<.65?'ОГОНЬ ЧЕРЕЗ '+Math.max(0,e.clock).toFixed(1)+'с':'УГРОЗА'):e.kind==='exit'?'ВЫХОД':(e.side==='left'?'ЛЕВАЯ':'ПРАВАЯ')+' '+(3-e.hp)+'/3';if(p.d<zbuffer[clamp(Math.floor(p.x),0,639)]+.1)ctx.fillText(label,p.x,top-6);ctx.textAlign='left';}}
  if(s.light){const beam=ctx.createRadialGradient(320,180,15,320,180,170);beam.addColorStop(0,'rgba(255,231,175,.18)');beam.addColorStop(1,'rgba(255,231,175,0)');ctx.fillStyle=beam;ctx.fillRect(0,0,w,h);}const vign=ctx.createRadialGradient(320,180,90,320,180,380);vign.addColorStop(0,'#0000');vign.addColorStop(1,'#020810b0');ctx.fillStyle=vign;ctx.fillRect(0,0,w,h);
  weapon(now);if(s.tracer>0&&s.tracerPoint){ctx.strokeStyle=`rgba(255,216,139,${s.tracer*5})`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(s.ads?320:390,s.ads?180:270);ctx.lineTo(s.tracerPoint.x,s.tracerPoint.y);ctx.stroke();ctx.fillStyle='#ffe1a3';ctx.fillRect(s.tracerPoint.x-1,s.tracerPoint.y-1,2,2);}if(s.wounded){ctx.fillStyle=`rgba(155,8,19,${.17+.14*(1+Math.sin(now*.009))/2})`;ctx.fillRect(0,0,w,h);const g=ctx.createRadialGradient(320,180,60,320,180,310);g.addColorStop(0,'#80000000');g.addColorStop(1,'#ac182a99');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);}if(s.woundFlash){ctx.fillStyle=`rgba(225,33,40,${s.woundFlash*.4})`;ctx.fillRect(0,0,w,h);}if(s.hitFlash){ctx.strokeStyle='#ffddb0';ctx.lineWidth=2;for(const [dx,dy] of [[-1,-1],[1,-1],[-1,1],[1,1]]){ctx.beginPath();ctx.moveTo(320+dx*6,180+dy*6);ctx.lineTo(320+dx*11,180+dy*11);ctx.stroke();}}
  ui('fpsReticle').hidden=s.inspecting||!s.ads||s.raised||!!s.reload||!!s.bandaging;ui('fpsClock').textContent=tutorial?'БЕЗ КАРЬЕРНЫХ ШТРАФОВ':Math.max(0,(combat?240:90)-s.elapsed).toFixed(1)+' с';ui('fpsWeapon').textContent=(s.bandaging?'БИНТ '+s.bandaging.toFixed(1)+' с':s.reload?'МАГАЗИН '+s.reload.toFixed(1)+' с':s.raised?'СТВОЛ ВВЕРХ':s.ads?'ЧЕРЕЗ ПРИЦЕЛ':'ОТ БЕДРА')+' / '+(exercise==='magazine'?'ПАТРОНЫ: ОСМОТР R':s.ammo+' / '+(combat?12:30))+' / ЗАПАС '+s.reserve+(combat?' МАГ.':' ПАТР.');
  const ex=s.entities.find(e=>e.kind==='exit');ui('fpsCompass').textContent=ex?'ВЫХОД '+(Math.abs(bearing(ex))<.4?'↑':bearing(ex)>0?'→':'←')+' '+Math.round(Math.hypot(ex.x-s.x,ex.y-s.y))+' м':'';ui('fpsObjective').textContent=combat?'СЕКТОР '+s.round+'/3 · '+(cover(s)?'УКРЫТИЕ':'ПОД ОГНЁМ')+' · ЗДОРОВЬЕ '+Math.max(0,s.health)+'% · ПОПАДАНИЯ '+s.damageHits+'/3 · КРОВОПОТЕРЯ '+(s.wounded?s.bleed.toFixed(1)+'с':'НЕТ'):exercise==='third'?'СЕРИЯ '+(s.series+1)+' · Л '+s.hits[0].length+'/3 / П '+s.hits[1].length+'/3 · '+(s.transferCrossed?'ПЕРЕНОС ЗАЧТЁН':'БЕЗОПАСНЫЙ ПЕРЕНОС'):exercise==='front'?'СЕЙЧАС '+(s.expectedSide==='left'?'ЛЕВАЯ':'ПРАВАЯ')+' ТРОЙКА':exercise==='judgement'?'ОБЗОР КОМНАТЫ '+s.scan.size+'/3 · ВРАГ / МИРНЫЙ / ЗАЛОЖНИК':exercise==='moving'?'СЛЕДИТЕ ЗА ДВИЖЕНИЕМ · ТРОЙКИ ПОПАДАНИЙ':'НАЙДИТЕ И ПОРАЗИТЕ ПАРУ';ui('fpsScore').textContent='УНИЧТОЖЕНО '+s.destroyed+' · '+s.points+' ОЧКОВ · '+s.misses+' ПРОМАХОВ';ui('fpsMessage').textContent=s.feedbackTime?s.feedback:'';groupDisplay();
 }
 function groupDisplay(){const c=ui('fpsGrouping'),g=c.getContext('2d');g.fillStyle='#0b151e';g.fillRect(0,0,130,100);g.strokeStyle='#a99d7a';g.strokeRect(8,18,72,72);g.font='10px monospace';g.fillStyle='#edd7a9';g.fillText('КУЧНОСТЬ',4,12);const hits=s.hits.flat().length?s.hits.flat():s.lastGroup||[];let spread=0;for(const a of hits){g.fillStyle='#ffcc73';g.beginPath();g.arc(44+a.x*60,54+a.y*60,2.5,0,TAU);g.fill();for(const b of hits)spread=Math.max(spread,Math.hypot(a.x-b.x,a.y-b.y));}g.fillText(hits.length+' точек',84,45);g.fillText((spread*100).toFixed(1),84,65);g.fillText('ед.*',88,78);c.title='Условная шкала мишени; максимальное расстояние между точками';}
 function weapon(now){const bob=s.active&&keys.size?Math.sin(now*.008)*2:0;let x=s.ads?320:390,y=s.ads?300:342;ctx.save();ctx.translate(x,y+bob+-s.recoil*14);if(!s.ads){ctx.scale(.9,.72);ctx.translate(0,10);}if(s.raised){ctx.translate(115,-45);ctx.rotate(-.4);}if(s.lean)ctx.rotate(s.lean==='left'?-.06:.06);if(s.reload){const t=1-s.reload/1.5;ctx.translate(35,Math.sin(t*PI)*70);ctx.rotate(.18);}ctx.fillStyle='#141e24';ctx.strokeStyle='#61757d';ctx.lineWidth=2;ctx.fillRect(-24,-55,48,90);ctx.strokeRect(-24,-55,48,90);ctx.fillStyle='#334b56';ctx.fillRect(-19,-71,38,60);ctx.fillStyle='#92a4a6';ctx.fillRect(-16,-71,3,55);ctx.fillStyle='#0d151b';ctx.fillRect(-7,-120,14,68);ctx.fillStyle='#75898b';ctx.fillRect(-8,-109,2,53);ctx.fillStyle='#15252c';ctx.fillRect(-15,-85,30,14);ctx.strokeStyle='#96aaa6';ctx.strokeRect(-12,-87,24,13);ctx.fillStyle='#9c785d';ctx.fillRect(-42,-15,21,50);ctx.fillRect(23,7,27,51);ctx.fillStyle='#263640';ctx.fillRect(-44,22,26,60);ctx.fillRect(23,35,30,52);if(s.reload){ctx.fillStyle='#6b7f7b';ctx.fillRect(-11,20,22,44);}if(s.flash){ctx.fillStyle='#fff2bb';ctx.beginPath();ctx.moveTo(0,-145);ctx.lineTo(10,-120);ctx.lineTo(21,-126);ctx.lineTo(7,-113);ctx.lineTo(0,-101);ctx.lineTo(-10,-116);ctx.lineTo(-20,-129);ctx.closePath();ctx.fill();}ctx.restore();
  if(s.ads&&!s.raised&&!s.reload){ctx.strokeStyle='#9faea7';ctx.lineWidth=3;ctx.strokeRect(306,165,28,30);ctx.fillStyle='#f4bf69';ctx.fillRect(319,178,2,5);}
  if(s.bandaging){ctx.save();ctx.translate(320+Math.sin(now*.01)*4,285);ctx.fillStyle='#af886b';ctx.fillRect(-60,0,120,28);ctx.fillStyle='#e9debd';for(let i=0;i<4;i++)ctx.fillRect(-18+i*9,-3,6,36);ctx.fillStyle='#382929';ctx.fillRect(-60,38,120,5);ctx.fillStyle='#d5c59c';ctx.fillRect(-60,38,120*(1-s.bandaging/3.1),5);ctx.restore();}
 }
 function loop(now){if(s.done)return;const dt=Math.min(.04,(now-last)/1000);last=now;if(s.active)update(dt);if(s.done)return;draw(now);raf=requestAnimationFrame(loop);}
 pair();if(tutorial){s.entities=[{kind:'target',side:'left',x:13.5,y:8.5,hp:30}];s.yaw=0;s.feedback=lessons[0];s.feedbackTime=10;}raf=requestAnimationFrame(loop);return {state:s,dispose};
}
