// Two decision drills: simulated cover before F, and inspecting an approximate magazine before exposure.
export function mountHabit(host,{mode,onExit,onFinish,seed=0}){
 if(!['bandage','magazine'].includes(mode))throw Error('Unknown drill');
 const root=document.createElement('section');root.className='training habit';root.innerHTML=`<canvas id="habitCanvas" tabindex="0"></canvas><div class="habit-top" id="habitStats"></div><button id="habitExit">В меню</button><div class="habit-brief"><img src="assets/alvarez-portrait.png" alt="Гало Альварес"><div><b id="habitTitle"></b><p id="habitInstruction"></p></div></div><div id="magazineGraphic" hidden><span>ОСМОТР МАГАЗИНА — примерная наполненность</span><div class="mag-shell"><div class="mag-fill"></div></div><span id="magEstimate"></span></div><div id="habitWrap" hidden><div class="wrap-arm">✋　▰▰　бинт наматывается　▰▰</div><div class="wrap-progress"></div></div><div class="habit-bottom" id="habitStatus"></div><button id="habitStart">Начать · Esc — освободить мышь</button>`;host.replaceChildren(root);
 const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),start=root.querySelector('#habitStart'),instruction=root.querySelector('#habitInstruction');
 const s={mode,seed,x:0,startX:0,coverX:0,cover:false,bandaging:0,bandageSafe:false,reloading:0,ammo:0,reserve:90,inspect:false,inspecting:false,shots:0,completed:0,mistakes:0,streak:0,round:0,elapsed:0,active:false,done:false,feedback:'',required:0,exposed:false,exposure:0};
 const abort=new AbortController(),opts={signal:abort.signal},keys=new Set();let raf,last=performance.now(),rDown=null,holdTimer=null;
 root.querySelector('#habitTitle').textContent=mode==='bandage'?'ЧЕТВЁРТАЯ СМЕНА · УКРЫТИЕ И ПЕРЕВЯЗКА':'ПЯТАЯ СМЕНА · ПРОВЕРКА МАГАЗИНА';
 function coverNow(){return Math.abs(s.x-s.coverX)<.55;}
 function note(message){s.feedback=message;drawText();}
 function drawText(){
  instruction.textContent=(s.feedback?s.feedback+' ':'')+(mode==='bandage'?(s.round<2?'Ранены. Найдите укрытие A/D, затем F — перевязка займёт время. Во время неё двигаться можно, стрелять нельзя.':'Ранены. Оцените угрозу и найдите безопасное место перед F.'):s.round<2?'Удерживайте R для осмотра магазина. Отпустите; короткое R меняет магазин. Выход — W.':'Перед выходом оцените запас патронов. W — выход.');
 }
 function nextScenario(){
  if(s.completed+s.mistakes>=8){finish('scenarios_done');return;}
  s.round++;s.feedback='';s.x=0;s.startX=0;s.coverX=mode==='bandage'&&s.round%4===0?0:((s.round+seed)%2?2.2:-2.2);s.cover=coverNow();s.bandaging=0;s.bandageSafe=false;s.reloading=0;s.inspect=false;s.inspecting=false;s.exposed=false;s.exposure=0;keys.clear();
  if(mode==='magazine'){s.required=[3,5,2,4,3,5,4,3][(s.round+seed-1)%8];s.ammo=[0,1,18,2,23,1,14,9][(s.round+seed-1)%8];s.reserve=90;root.querySelector('#magazineGraphic').hidden=true;}
  drawText();
 }
 function finish(reason){if(s.done)return;dispose();onFinish({reason,duration:s.elapsed,points:s.completed*100-s.mistakes*25,completed:s.completed,mistakes:s.mistakes,streak:s.streak,round:s.round,destroyed:s.completed,resign:0,killed:0});}
 function dispose(){s.done=true;abort.abort();clearTimeout(holdTimer);cancelAnimationFrame(raf);if(document.pointerLockElement===canvas)document.exitPointerLock();}
 root.querySelector('#habitExit').onclick=()=>{dispose();onExit();};
 start.onclick=()=>{s.active=true;last=performance.now();start.hidden=true;canvas.focus();canvas.requestPointerLock?.().catch(()=>{});};
 document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==canvas&&!s.done){s.active=false;keys.clear();start.hidden=false;start.textContent='Продолжить';}},opts);
 window.addEventListener('blur',()=>{s.active=false;keys.clear();start.hidden=false;},opts);
 function mistake(why){s.mistakes++;s.streak=0;nextScenario();if(!s.done)note(why+' Следующая ситуация.');}
 function success(why){s.completed++;s.streak++;nextScenario();if(!s.done)note(why+' Следующая ситуация.');}
 function checkMagazine(){s.inspect=true;s.inspecting=true;const graphic=root.querySelector('#magazineGraphic');graphic.hidden=false;graphic.querySelector('.mag-fill').style.height=`${Math.round(s.ammo/30*100)}%`;root.querySelector('#magEstimate').textContent=s.ammo===0?'Пусто':s.ammo<=5?'Почти пусто':s.ammo<=14?'Меньше половины':s.ammo<=23?'Больше половины':'Почти полный';note('Оцените магазин по рисунку. Точное число не показывается.');}
 function shortR(){if(s.reloading)return;if(s.inspect&&s.ammo>=s.required){s.elapsed+=3;}s.reloading=1.4;s.inspecting=false;root.querySelector('#magazineGraphic').hidden=true;note('Меняю магазин… дождитесь завершения.'+(s.inspect&&s.ammo>=s.required?' Лишняя замена: +3 с.':''));}
 function rRelease(){if(rDown===null)return;const held=performance.now()-rDown;clearTimeout(holdTimer);rDown=null;if(held>=550){if(!s.inspecting)checkMagazine();}else shortR();}
 function bandage(){if(s.bandaging)return;s.bandaging=3.2;s.bandageSafe=coverNow();root.querySelector('#habitWrap').hidden=false;note(s.bandageSafe?'Перевязка началась в укрытии. Можно двигаться, но не покидайте укрытие до конца.':'Перевязка началась на открытом месте. Двигайтесь за укрытие, пока не поздно.');}
 function expose(){if(s.exposed)return;s.exposed=true;s.exposure=1.5;if(!s.inspect){mistake('Вышли, не проверив магазин.');return;}if(s.reloading){mistake('Вышли до окончания замены магазина.');return;}if(s.ammo<s.required){mistake('Патронов оказалось недостаточно для целей.');return;}note('Патронов достаточно. Поражайте подсвеченные мишени ЛКМ.');}
 window.addEventListener('keydown',e=>{if(!s.active||s.done)return;if(['KeyW','KeyA','KeyD','KeyF','KeyR'].includes(e.code))e.preventDefault();if(e.repeat)return;if(['KeyA','KeyD','KeyW'].includes(e.code))keys.add(e.code);if(mode==='bandage'&&e.code==='KeyF')bandage();if(mode==='magazine'&&e.code==='KeyR'&&rDown===null){rDown=performance.now();holdTimer=setTimeout(()=>{if(rDown!==null&&s.active)checkMagazine();},550);}},opts);
 window.addEventListener('keyup',e=>{keys.delete(e.code);if(mode==='magazine'&&e.code==='KeyR'&&s.active)rRelease();},opts);
 canvas.addEventListener('mousedown',e=>{if(!s.active||e.button!==0)return;e.preventDefault();if(mode==='bandage'){if(s.bandaging)note('Руки заняты: пока мотаете бинт, стрелять нельзя.');else{s.shots++;note('Здесь отрабатываем решение об укрытии, а не стрельбу.');}}else if(s.exposed&&s.required>0){s.shots++;s.ammo--;s.required--;if(s.required<=0)success('Цели поражены после проверки магазина.');else if(s.ammo<=0)mistake('Магазин опустел до поражения целей.');}},opts);
 canvas.addEventListener('contextmenu',e=>e.preventDefault(),opts);
 function render(now){const w=canvas.width=root.clientWidth,h=canvas.height=root.clientHeight;ctx.fillStyle='#1a2930';ctx.fillRect(0,0,w,h);ctx.fillStyle='#354249';ctx.fillRect(0,h*.58,w,h*.42);ctx.fillStyle='#535f61';for(let i=0;i<8;i++)ctx.fillRect(i*w/7, h*.6, 2,h*.4);let cx=w/2+s.coverX*95;ctx.fillStyle='#a4a097';ctx.fillRect(cx-78,h*.4,156,h*.42);ctx.fillStyle='#243137';ctx.fillRect(cx-57,h*.46,114,h*.32);ctx.fillStyle='#ffe0a3';ctx.font='18px sans-serif';ctx.fillText(mode==='bandage'?'УКРЫТИЕ':'ЦЕЛИ',cx-45,h*.43);if(mode==='bandage'){ctx.fillStyle='#f4d281';ctx.beginPath();ctx.arc(w/2+s.x*95,h*.83,19,0,Math.PI*2);ctx.fill();ctx.font='bold 17px sans-serif';ctx.fillStyle='#f8f4e9';ctx.fillText('ВЫ',w/2+s.x*95-12,h*.88);ctx.strokeStyle='#f6d37d';ctx.lineWidth=3;ctx.strokeRect(cx-78,h*.4,156,h*.42);}if(mode==='magazine'){ctx.fillStyle=s.exposed?'#d47751':'#8daa9c';ctx.fillRect(w*.8,h*.38,95,h*.2);ctx.fillStyle='white';ctx.fillText(s.exposed?`Осталось целей: ${s.required}`:'РУБЕЖ',w*.77,h*.35);}
  if(mode==='bandage'&&s.bandaging){ctx.fillStyle=`rgba(145,8,18,${.37+Math.sin(now/70)*.08})`;ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w*.5+Math.sin(now/85)*11,h*.74);ctx.rotate(Math.sin(now/180)*.16);ctx.fillStyle='#d3aa8a';ctx.fillRect(-50,-70,100,170);ctx.fillStyle='#e9e2ce';ctx.fillRect(-48,-25,96,36);ctx.restore();root.querySelector('.wrap-progress').style.width=`${Math.round((1-s.bandaging/3.2)*100)}%`;}
  root.querySelector('#habitStats').textContent=`${mode==='bandage'?'ПЕРЕВЯЗКА':'МАГАЗИН'} · Ситуация ${s.round}/8 · Успехи ${s.completed} · Ошибки ${s.mistakes} · Серия ${s.streak}`;
  root.querySelector('#habitStatus').textContent=mode==='bandage'?`${coverNow()?'ЗА УКРЫТИЕМ':'НА ОТКРЫТОМ МЕСТЕ'} · ${s.bandaging?'Перевязка '+s.bandaging.toFixed(1)+' с':'F — начать перевязку'} · A/D — движение`:`ЦЕЛЕЙ ВПЕРЕДИ: ${s.required} · ${s.inspect?'МАГАЗИН ОСМОТРЕН':'МАГАЗИН НЕ ПРОВЕРЕН'} · ${s.reloading?'Замена '+s.reloading.toFixed(1)+' с':'Удерживать R — осмотр / короткое R — замена'} · W — выйти к мишеням`;}
 function loop(now){if(s.done)return;const dt=Math.min(.05,(now-last)/1000);last=now;if(s.active){s.elapsed+=dt;if(mode==='bandage'){s.x=Math.max(-3,Math.min(3,s.x+((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0))*dt*4));s.cover=coverNow();if(s.bandaging){if(!s.cover)s.bandageSafe=false;s.bandaging=Math.max(0,s.bandaging-dt);if(!s.bandaging){root.querySelector('#habitWrap').hidden=true;if(s.cover&&s.bandageSafe)success('Перевязка закончена в укрытии.');else mistake('Перевязка была начата или продолжалась на открытом месте.');}}}else{if(s.reloading){s.reloading=Math.max(0,s.reloading-dt);if(!s.reloading){s.ammo=30;s.inspect=false;s.inspecting=false;note('Магазин заменён. Перед выходом проверьте его.');}}if(keys.has('KeyW'))expose();if(s.exposed&&s.exposure){s.exposure=Math.max(0,s.exposure-dt);if(!s.exposure)mistake('Задержались на открытом рубеже.');}}if(s.elapsed>=180){finish('time_limit');return;}}render(now);raf=requestAnimationFrame(loop);}
 nextScenario();raf=requestAnimationFrame(loop);return {state:s,dispose,nextScenario};
}
