// Original top-down pixel-noir action drills. Geometry, projectiles and scores share one simulation.
import {playShot} from './shot-sound.js';
const W=27,H=17,T=32, HOLD=550;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function makeMaze(variant){
 const map=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>x===0||y===0||x===W-1||y===H-1?'#':'.'));
 for(const x of [9,18])for(let y=1;y<H-1;y++)if(![3,9,14].includes(y))map[y][x]='#';
 for(const y of [7,12])for(let x=1;x<W-1;x++)if(![4,13,23].includes(x))map[y][x]='#';
 for(const [x,y] of [[4,5],[5,5],[12,4],[14,10],[20,4],[22,10],[6,14],[24,14]])map[y][x]='C';
 // Move a few crates per layout, without sealing doors.
 if(variant%2){map[5][4]='.';map[4][4]='C';map[10][22]='.';map[10][21]='C';}
 return map.map(row=>row.join(''));
}
function wall(map,x,y){return map[Math.floor(y)]?.[Math.floor(x)]??'#';}
function solid(map,x,y){return wall(map,x,y)!=='.';}
function visible(map,a,b){const length=Math.hypot(a.x-b.x,a.y-b.y),steps=Math.ceil(length*12);for(let i=1;i<steps;i++){const x=a.x+(b.x-a.x)*i/steps,y=a.y+(b.y-a.y)*i/steps;if(solid(map,x,y))return false;}return true;}
function covered(s){return !s.enemies.some(e=>e.hp>0&&visible(s.maze,{x:s.x,y:s.y},e));}
function audioEngine(){let context=null,timer=null,step=0;const chords=[[130.81,155.56,196],[110,146.83,174.61],[116.54,146.83,185],[98,123.47,155.56]];function play(){if(!context)return;const time=context.currentTime,notes=chords[Math.floor(step/4)%chords.length];for(const f of notes){const o=context.createOscillator(),g=context.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(.085,time+.25);g.gain.exponentialRampToValueAtTime(.0001,time+1.65);o.connect(g).connect(context.destination);o.start(time);o.stop(time+1.7);}if(step%2===0){const o=context.createOscillator(),g=context.createGain();o.type='triangle';o.frequency.setValueAtTime(notes[0]/2,time);g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(.027,time+.02);g.gain.exponentialRampToValueAtTime(.0001,time+.28);o.connect(g).connect(context.destination);o.start(time);o.stop(time+.3);}step++;}return {async toggle(){if(context){clearInterval(timer);await context.close();context=null;return false;}context=new (window.AudioContext||window.webkitAudioContext)();await context.resume();if(context.state!=='running'){await context.close();context=null;throw Error('аудиоконтекст заблокирован');}play();timer=setInterval(play,800);return true;},stop(){clearInterval(timer);if(context)context.close();context=null;}};}
export function mountHabit(host,{mode,onExit,onFinish,seed=0}){
 if(!['bandage','magazine'].includes(mode))throw Error('Unknown drill');
 const root=document.createElement('section');root.className='training habit';root.innerHTML=`<canvas id="habitCanvas" tabindex="0" width="864" height="544" aria-label="Лабиринт смены"></canvas><div class="habit-top" id="habitStats"></div><div class="habit-actions"><button id="habitMusic" title="Оригинальная синтезированная музыка">♫ Музыка: выкл.</button><button id="habitExit">В меню</button></div><div class="habit-brief"><div class="habit-kicker" id="habitTitle"></div><p id="habitHint">Задача смены указана ниже.</p><p id="habitInstruction"></p></div><div id="magazineGraphic" hidden><span>ОСМОТР · примерная наполненность</span><div class="mag-shell"><div class="mag-fill"></div></div><span id="magEstimate"></span></div><div id="habitWrap" hidden><div class="wrap-arm">▰ бинт ▰</div><div class="wrap-progress"></div></div><div class="habit-bottom" id="habitStatus"></div><button id="habitStart">НАЧАТЬ ВЫЛАЗКУ</button>`;host.replaceChildren(root);
 const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),start=root.querySelector('#habitStart'),sound=audioEngine(),keys=new Set(),abort=new AbortController(),opts={signal:abort.signal};
 const s={mode,seed,maze:makeMaze(seed),x:3.5,y:3.5,health:100,wounded:false,healed:false,bandaging:0,bandageSafe:false,reloading:0,ammo:0,reserve:3,inspect:false,inspecting:false,shots:0,completed:0,mistakes:0,streak:0,round:1,elapsed:0,active:false,done:false,feedback:'',required:0,enemyClock:.65,bullets:[],enemies:[],aimX:5.5,aimY:3.5,flash:0,impaired:0,extraction:{x:25.5,y:14.5}};
 let raf=0,last=performance.now(),rDown=null,holdTimer=null,feedbackTime=0,beat=0;
 const stat=root.querySelector('#habitStats'),status=root.querySelector('#habitStatus'),instruction=root.querySelector('#habitInstruction'),mag=root.querySelector('#magazineGraphic');
 root.querySelector('#habitTitle').textContent=mode==='bandage'?'04 / КРАСНЫЙ КОРИДОР':'05 / ПОСЛЕДНИЙ МАГАЗИН';
 function note(text){s.feedback=text;feedbackTime=5;}
 function scenario(){s.maze=makeMaze(seed+s.round);s.x=3.5;s.y=3.5;s.health=100;s.wounded=false;s.healed=false;s.bandaging=0;s.bandageSafe=false;s.reloading=0;s.inspect=false;s.inspectedBeforeContact=false;s.inspecting=false;s.bullets=[];s.flash=0;s.impaired=0;s.enemyClock=.65;s.enemies=[{x:6.5,y:3.5,hp:2,clock:.7},{x:13.5,y:3.5,hp:2,clock:1.6},{x:22.5,y:9.5,hp:2,clock:1.9}];s.extraction={x:25.5,y:14.5};s.required=s.enemies.reduce((n,e)=>n+e.hp,0);s.ammo=[3,11,3,9][(seed+s.round-1)%4];s.reserve=2;s.shots=0;s.tookDamage=false;mag.hidden=true;root.querySelector('#habitWrap').hidden=true;keys.clear();note(mode==='bandage'?'Найдите маршрут, переживите обстрел и перевяжитесь за настоящим укрытием.':'Осмотрите магазин перед контактом. Решите, хватит ли патронов; затем найдите выход.');}
 function dispose(){if(s.done)return;s.done=true;abort.abort();clearTimeout(holdTimer);cancelAnimationFrame(raf);sound.stop();keys.clear();}
 function finish(reason){if(s.done)return;dispose();onFinish({reason,duration:s.elapsed,points:Math.max(0,s.completed*180+s.streak*30-s.mistakes*35-Math.floor(s.elapsed/3)),completed:s.completed,mistakes:s.mistakes,streak:s.streak,round:s.round,destroyed:s.shots,resign:0,killed:0});}
 function success(){s.completed++;s.streak++;if(s.round>=3){finish('extracted');return;}s.round++;scenario();note('Маршрут пройден. Новый участок — другая раскладка и новые угрозы.');}
 function failure(why){s.mistakes++;s.streak=0;if(s.round>=3){finish('time_limit');return;}s.round++;scenario();note(why+' Новый участок.');}
 root.querySelector('#habitExit').onclick=()=>{dispose();onExit();};root.querySelector('#habitMusic').onclick=async e=>{const button=e.currentTarget;try{button.disabled=true;const on=await sound.toggle();button.textContent=on?'♫ Музыка: вкл.':'♫ Музыка: выкл.';button.setAttribute('aria-pressed',String(on));button.dataset.audioState=on?'running':'closed';if(!on)note('Музыка выключена.');}catch(error){button.textContent='♫ Звук недоступен';button.setAttribute('aria-pressed','false');button.dataset.audioState='blocked';note('Браузер не запустил звук: '+error.message);}finally{button.disabled=false;}};
 start.onclick=()=>{s.active=true;last=performance.now();start.hidden=true;canvas.focus();};
 window.addEventListener('blur',()=>{s.active=false;keys.clear();start.hidden=false;start.textContent='ПРОДОЛЖИТЬ';},opts);
 const canvasPos=e=>{const b=canvas.getBoundingClientRect();return {x:(e.clientX-b.left)/b.width*W,y:(e.clientY-b.top)/b.height*H};};
 canvas.addEventListener('mousemove',e=>{const p=canvasPos(e);s.aimX=p.x;s.aimY=p.y;},opts);
 function fire(){if(!s.active||s.done)return;if(s.bandaging){note('Пока бинтуете руку, стрелять нельзя.');return;}if(s.reloading){note('Дождитесь окончания замены.');return;}if(s.ammo<=0){note('Пустой магазин. Короткое R — сменить; после смены снова осмотрите.');return;}s.ammo--;s.shots++;playShot();s.flash=.15;s.tracer=.22;const angle=Math.atan2(s.aimY-s.y,s.aimX-s.x),target={x:s.x+Math.cos(angle)*25,y:s.y+Math.sin(angle)*25};let chosen=null,best=Infinity;for(const e of s.enemies)if(e.hp>0){const dist=Math.hypot(e.x-s.x,e.y-s.y),perp=Math.abs((e.x-s.x)*Math.sin(angle)-(e.y-s.y)*Math.cos(angle));if(perp<.42&&dist<best&&visible(s.maze,{x:s.x,y:s.y},e)){chosen=e;best=dist;}}let impact=chosen?{x:chosen.x,y:chosen.y}:target;if(!chosen){for(let t=0;t<25;t+=.05){const x=s.x+Math.cos(angle)*t,y=s.y+Math.sin(angle)*t;if(solid(s.maze,x,y)){impact={x,y};break;}}}s.tracerEnd=impact;if(chosen){chosen.hp--;note(chosen.hp?'Попадание. Цель всё ещё активна.':'Угроза подавлена. Продолжайте к выходу.');}else note('Промах. Патрон потрачен — поправьте прицел.');s.required=s.enemies.reduce((n,e)=>n+e.hp,0);if(s.ammo===0&&s.reserve===0&&s.required>0)note('Боезапас исчерпан. Ищите укрытие и маршрут обхода.');}
 canvas.addEventListener('mousedown',e=>{if(e.button===0){e.preventDefault();fire();}},opts);canvas.addEventListener('contextmenu',e=>e.preventDefault(),opts);
 function inspect(){s.inspect=true;s.inspectedBeforeContact ||= s.shots===0;s.inspecting=true;mag.hidden=false;mag.querySelector('.mag-fill').style.height=`${Math.round(s.ammo/12*100)}%`;root.querySelector('#magEstimate').textContent=s.ammo===0?'Пусто':s.ammo<=3?'Почти пусто':s.ammo<=6?'Около половины':'Больше половины';note('Прикиньте остаток визуально. Точное число скрыто.');}
 function shortR(){if(s.reloading||s.reserve<=0){note('Запасных магазинов больше нет.');return;}if(s.inspect&&s.ammo>=s.required){s.elapsed+=3;note('Достаточного магазина менять не требовалось: потеря времени.');}else note('Меняю магазин — найдите безопасное место.');s.reloading=1.45;s.inspecting=false;mag.hidden=true;}
 function rRelease(){if(rDown===null)return;const t=performance.now()-rDown;clearTimeout(holdTimer);rDown=null;if(t>=HOLD){if(!s.inspecting)inspect();}else shortR();}
 function bandage(){if(s.bandaging||!s.wounded){note(s.wounded?'Перевязка уже идёт.':'Вы не ранены — бинт пока не нужен.');return;}s.bandaging=3.1;s.bandageSafe=covered(s);root.querySelector('#habitWrap').hidden=false;note(s.bandageSafe?'Перевязка. Не выходите из укрытия до завершения.':'Открытое место! Сначала найдите укрытие.');}
 window.addEventListener('keydown',e=>{if(!s.active||s.done)return;if(['KeyW','KeyA','KeyS','KeyD','KeyF','KeyR','Space'].includes(e.code))e.preventDefault();if(e.repeat)return;if(['KeyW','KeyA','KeyS','KeyD'].includes(e.code))keys.add(e.code);if(e.code==='KeyF'&&mode==='bandage')bandage();if(e.code==='KeyR'&&rDown===null){rDown=performance.now();holdTimer=setTimeout(()=>{if(rDown!==null&&s.active)inspect();},HOLD);}},opts);
 window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='KeyR'&&s.active)rRelease();},opts);
 function move(dt){let dx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),dy=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0);const n=Math.hypot(dx,dy)||1;dx=dx/n*dt*(s.wounded?1.65:2.85);dy=dy/n*dt*(s.wounded?1.65:2.85);for(const [axis,d] of [['x',dx],['y',dy]]){const nx=axis==='x'?s.x+d:s.x,ny=axis==='y'?s.y+d:s.y;if(![[nx-.22,ny-.22],[nx+.22,ny-.22],[nx-.22,ny+.22],[nx+.22,ny+.22]].some(([x,y])=>solid(s.maze,x,y)))s[axis]+=d;}}
 function enemyStep(dt){s.enemyClock-=dt;for(const e of s.enemies){if(e.hp<=0)continue;e.clock-=dt;if(e.clock<=0&&visible(s.maze,{x:s.x,y:s.y},e)){e.clock=1.8+((s.round+seed)%3)*.22;const a=Math.atan2(s.y-e.y,s.x-e.x);s.bullets.push({x:e.x,y:e.y,vx:Math.cos(a)*6.2,vy:Math.sin(a)*6.2});s.enemyClock=1.8;}}for(const b of s.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;if(solid(s.maze,b.x,b.y)){b.dead=true;continue;}if(Math.hypot(b.x-s.x,b.y-s.y)<.34){b.dead=true;s.health-=33;s.wounded=true;s.tookDamage=true;s.impaired=2.4;note('РАНЕНИЕ. Экран краснеет. Найдите укрытие; F — перевязка.');if(s.health<=0){failure('Не удалось выйти из-под огня.');return;}}}s.bullets=s.bullets.filter(b=>!b.dead);}
 function update(dt){s.elapsed+=dt;move(dt);enemyStep(dt);if(s.done)return;if(s.bandaging){if(!covered(s))s.bandageSafe=false;s.bandaging=Math.max(0,s.bandaging-dt);if(!s.bandaging){root.querySelector('#habitWrap').hidden=true;if(s.bandageSafe&&covered(s)){s.wounded=false;s.healed=true;s.health=Math.min(100,s.health+42);note('Перевязка завершена в укрытии. Двигайтесь к выходу.');}else{note('Перевязка на линии огня не засчитана. Найдите укрытие.');s.mistakes++;s.streak=0;}}}if(s.reloading){s.reloading=Math.max(0,s.reloading-dt);if(!s.reloading){s.ammo=12;s.reserve--;s.inspect=false;note('Магазин заменён. Для оценки запаса снова удерживайте R.');}}s.impaired=Math.max(0,s.impaired-dt);s.flash=Math.max(0,s.flash-dt);s.tracer=Math.max(0,(s.tracer||0)-dt);feedbackTime=Math.max(0,feedbackTime-dt);if(Math.hypot(s.x-s.extraction.x,s.y-s.extraction.y)<.7){if(mode==='bandage'&&s.tookDamage&&(!s.healed||s.wounded)){note('После ранения требуется безопасная перевязка.');}else if(mode==='magazine'&&(!s.inspect||!s.inspectedBeforeContact)){note('Оцените магазин до первого выстрела и после замены.');}else if(mode==='magazine'&&s.required>0){note('Остались активные угрозы. Избегайте огня или подавите их.');}else success();}if(s.elapsed>=180)finish('time_limit');}
 function draw(now){const cw=canvas.width/W,ch=canvas.height/H;ctx.fillStyle='#080f16';ctx.fillRect(0,0,canvas.width,canvas.height);
 for(let y=0;y<H;y++)for(let x=0;x<W;x++){const c=s.maze[y][x],px=x*cw,py=y*ch,noise=(x*17+y*29)%6;ctx.fillStyle=c==='#'?'#25343f':c==='C'?'#484543':(x+y)%2?'#17232b':'#1a2930';ctx.fillRect(px,py,cw,ch);if(c==='#'){ctx.fillStyle='#496071';ctx.fillRect(px,py,cw,3);ctx.fillStyle='#0c171e';ctx.fillRect(px+cw-4,py,4,ch);}else if(c==='C'){ctx.fillStyle='#ae815b';ctx.fillRect(px+4,py+4,cw-8,5);ctx.fillStyle='#242a2b';ctx.fillRect(px+4,py+ch-8,cw-8,4);}else if(noise===1){ctx.fillStyle='#344048';ctx.fillRect(px+7,py+13,3,2);}}
 // Lamplight and distant window glow, without hiding traversable geometry.
 const exit=s.extraction;ctx.fillStyle='#e0b773';ctx.fillRect(exit.x*cw-11,exit.y*ch-13,22,26);ctx.fillStyle='#161d23';ctx.fillRect(exit.x*cw-6,exit.y*ch-7,12,15);ctx.font='bold 10px monospace';ctx.fillStyle='#ffe5a6';ctx.fillText('ВЫХОД',exit.x*cw-16,exit.y*ch-18);
 for(const e of s.enemies)if(e.hp>0){const x=e.x*cw,y=e.y*ch;ctx.fillStyle='rgba(238,77,64,.14)';ctx.fillRect(x-20,y-20,40,40);ctx.fillStyle='#101317';ctx.fillRect(x-8,y-7,16,17);ctx.fillStyle='#c26859';ctx.fillRect(x-5,y-12,10,7);ctx.fillStyle='#f2ad78';ctx.fillRect(x-6,y-7,4,2);ctx.fillRect(x+3,y-7,4,2);ctx.fillStyle='#d16b5c';ctx.fillRect(x-11,y+12,e.hp*10,3);if(e.clock<.38){ctx.strokeStyle='#ec6755';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,17,0,Math.PI*2);ctx.stroke();}}
 for(const b of s.bullets){ctx.fillStyle='#fff0a6';ctx.fillRect(b.x*cw-3,b.y*ch-3,6,6);}const x=s.x*cw,y=s.y*ch;if(s.tracer>0&&s.tracerEnd){ctx.strokeStyle=`rgba(255,218,129,${Math.min(1,s.tracer*3.5)})`;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(s.tracerEnd.x*cw,s.tracerEnd.y*ch);ctx.stroke();ctx.fillStyle='#fff7df';ctx.fillRect(x-5,y-5,10,10);}ctx.fillStyle='rgba(244,198,128,.09)';ctx.beginPath();ctx.arc(x,y,90,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0a1014';ctx.fillRect(x-10,y-10,20,22);ctx.fillStyle=s.wounded?'#cc6d64':'#c8af84';ctx.fillRect(x-6,y-11,12,10);ctx.fillStyle='#e5b677';ctx.fillRect(x-11,y+11,22,4);ctx.strokeStyle='#e6c283';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);let a=Math.atan2(s.aimY-s.y,s.aimX-s.x);ctx.lineTo(x+Math.cos(a)*21,y+Math.sin(a)*21);ctx.stroke();ctx.strokeStyle='#f3dcab';ctx.lineWidth=1;ctx.beginPath();ctx.arc(s.aimX*cw,s.aimY*ch,6,0,Math.PI*2);ctx.stroke();ctx.fillStyle=covered(s)?'#8abbaa':'#d38f7b';ctx.font='bold 11px monospace';ctx.fillText(covered(s)?'УКРЫТИЕ':'ОТКРЫТО',x-23,y-20);
 // Wound disrupts vision; bandaging overlays the hand and a pulsating red vignette.
 if(s.wounded||s.bandaging){const alpha=s.bandaging?.28:clamp(.12+s.impaired*.1,.15,.42);ctx.fillStyle=`rgba(165,19,32,${alpha+Math.sin(now/110)*.04})`;ctx.fillRect(0,0,canvas.width,canvas.height);}if(s.bandaging){ctx.fillStyle='#b68b70';ctx.fillRect(canvas.width/2+Math.sin(now/95)*5-22,canvas.height*.76,44,115);ctx.fillStyle='#f1e2cb';ctx.fillRect(canvas.width/2-23,canvas.height*.81,46,17);root.querySelector('.wrap-progress').style.width=`${Math.round((1-s.bandaging/3.1)*100)}%`;}
 ctx.fillStyle='rgba(3,8,12,.18)';for(let y=0;y<canvas.height;y+=4)ctx.fillRect(0,y,canvas.width,1);
 stat.textContent=`${mode==='bandage'?'04 · КРАСНЫЙ КОРИДОР':'05 · ПОСЛЕДНИЙ МАГАЗИН'}  /  СЕКТОР ${s.round}/3  /  УСПЕХ ${s.completed}  /  ОШИБКИ ${s.mistakes}  /  ЗДОРОВЬЕ ${Math.max(0,Math.ceil(s.health))}%`;
 status.textContent=`${covered(s)?'● УКРЫТИЕ':'◆ ПОД ОГНЁМ'}  ·  ${s.wounded?'РАНЕНИЕ':'НЕ РАНЕНЫ'}  ·  ${s.bandaging?'БИНТ '+s.bandaging.toFixed(1)+'с':s.reloading?'ЗАМЕНА '+s.reloading.toFixed(1)+'с':s.inspect?'МАГАЗИН ОСМОТРЕН':'МАГАЗИН НЕ ОСМОТРЕН'}  ·  ${s.required?'УГРОЗЫ '+s.enemies.filter(e=>e.hp>0).length:'ПУТЬ К ВЫХОДУ'} · ЗАПАС ${s.reserve}`;
 instruction.textContent=mode==='bandage'?'WASD ходьба · мышь прицел · ЛКМ выстрел · F перевязка':'WASD ходьба · мышь прицел · ЛКМ выстрел · R держать осмотр / коротко замена';root.querySelector('#habitHint').textContent=feedbackTime?s.feedback:mode==='bandage'?(s.wounded?'Укройтесь от прямого огня и перевяжитесь клавишей F.':'Найдите выход. Ранение требует перевязки за укрытием.'):(s.reloading?'Подождите замены магазина, затем снова удерживайте R.':!s.inspect?'Удерживайте R, чтобы оценить запас до первого выстрела.':s.required?'Подавите угрозы или ищите безопасный маршрут к выходу.':'Идите к выходу.');}
 function loop(now){if(s.done)return;const dt=Math.min(.05,(now-last)/1000);last=now;if(s.active)update(dt);if(s.done)return;draw(now);raf=requestAnimationFrame(loop);}scenario();raf=requestAnimationFrame(loop);return {state:s,dispose,nextScenario:scenario};
}
