import {chooseWave,wrap} from './waves.js';
import {playShot} from './shot-sound.js';
// Perspective training scene. Owns input and lifecycle; never writes profile storage.
export function mountRange(host,{tutorial=false,exercise='circle',officers=99,onExit,onFinish}) {
 const c=document.createElement('canvas'); c.id='rangeCanvas';
 host.innerHTML=`<section class="training fps"><div class="fps-stats" id="stats"></div><button id="leaveRange">В меню</button><div id="coach" class="coach"><img src="assets/alvarez-portrait.png" alt="Гало Альварес"><div><small>CHIEF GALO ALVAREZ</small><h2 id="lessonTitle"></h2><p id="lessonText"></p><button id="nextLesson" hidden>Дальше</button></div></div><div class="fps-bottom" id="gunStatus"></div><div class="fps-help">WASD — шаги · мышь — взгляд · Space — поднять / вернуть · ПКМ — прицел · R — магазин · Esc — освободить мышь</div><button id="capture">Нажмите, чтобы войти в тир</button></section>`;
 const root=host.firstElementChild; root.prepend(c); const ctx=c.getContext('2d');
 const s={x:0,z:0,yaw:0,pitch:0,raised:true,aimed:false,ammo:30,reserve:90,elapsed:0,reload:0,recoil:0,destroyed:0,resign:0,killed:0,stage:0,passed:false,moved:new Set(),toggles:0,active:false,done:false,events:[],targets:[],ally:null,expectedSide:'left',orderErrors:0,history:[],wave:0,intermission:0,unnecessary:0,raisedTime:0};
 const abort=new AbortController(),opts={signal:abort.signal}; let raf,last=performance.now(),safeStart=null;
 const lessons=[
 ['1 / 9 · Осмотритесь','Начнём без стрельбы. Пройдите вперёд, назад и в обе стороны: W, S, A, D. Мышью осмотритесь.'],
 ['2 / 9 · Ствол вверх','Пробел — поднимите ствол. Ещё раз — верните к мишеням. Повторите это сейчас.'],
 ['3 / 9 · Одиночный огонь','Без ПКМ стреляете от бедра: ориентир — конец ствола, крестика нет. Совместите его с левой мишенью. Три отдельных нажатия ЛКМ — три попадания. Не торопитесь после отдачи.'],
 ['4 / 9 · Через прицел','Теперь удерживайте ПКМ и попадите в правую мишень. Смотрите через прицел, не поверх него.'],
 ['5 / 9 · Перезарядка','Нажмите R и дождитесь смены магазина. Во время перезарядки стрелять нельзя.'],
 ['6 / 9 · Свой на линии','Напарник между мишенями. Поднимите ствол пробелом, переведите взгляд через напарника на другую сторону и верните оружие пробелом. Не стреляйте в него.'],
 ['7 / 9 · Свободный перенос','Своих нет. Поразите обе мишени без подъёма ствола. На уже осмотренном свободном пути лишнее движение только мешает.'],
 ['8 / 9 · Свой сбоку','Напарник сбоку, мишени рядом. Поразите обе без подъёма. Проверяйте путь ствола, а не просто наличие формы.'],
 ['9 / 9 · Круговой обзор','Цели теперь могут быть сбоку и сзади. Найдите и поразите две пары. Слышите механизм? Повернитесь. Перед осмотром неизвестного сектора поднять ствол разумно — за это штрафа нет. Новая пара появляется только после обеих целей, в других местах.']];
 let audio;let speechEnabled=true;
 const voiceButton=document.createElement('button');voiceButton.textContent='Речь: вкл';voiceButton.style.cssText='position:absolute;right:20px;top:65px;z-index:20';root.append(voiceButton);voiceButton.onclick=()=>{speechEnabled=!speechEnabled;voiceButton.textContent=speechEnabled?'Речь: вкл':'Речь: выкл';if(!speechEnabled)window.speechSynthesis?.cancel();};
 function say(message){if(!speechEnabled||!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(message);u.lang='ru-RU';const voices=window.speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang.toLowerCase().startsWith('ru'))||null;u.rate=1.04;window.speechSynthesis.speak(u);}
 function cue(obj){try{audio ||= new AudioContext();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain(),pan=audio.createStereoPanner();pan.pan.value=Math.sin(angleTo(obj));osc.frequency.value=420;gain.gain.setValueAtTime(.07,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);osc.connect(gain).connect(pan).connect(audio.destination);osc.start();osc.stop(audio.currentTime+.18);}catch{}}
 function pair(){
  s.wave++;
  if(!s.ally)s.ally={x:0,y:1,z:7,status:'active'};if(!tutorial){const present=s.wave%3!==2;if(s.wave===1||present!==s.previousPresence){s.ally={x:Math.sin(s.yaw+.55)*7+s.x,y:1,z:Math.cos(s.yaw+.55)*7+s.z,status:present?'active':'gone'};if(s.active)note(present?'Смена схемы: сотрудник занял позицию справа от взгляда.':'Смена схемы: сотрудник покинул площадку.');}s.previousPresence=present;}
  if(!tutorial||s.stage===8){s.targets=chooseWave(s,s.history,null);if(!tutorial){const a=Math.atan2(s.targets[0].x-s.x,s.targets[0].z-s.z),b=Math.atan2(s.targets[1].x-s.x,s.targets[1].z-s.z),mid=a+wrap(b-a)/2;const scheme=(s.wave-1)%3;s.scheme=['between','absent','side'][scheme];if(scheme!==1){let bearing=scheme===0?mid:a-Math.sign(wrap(b-a))*.65;if(Math.abs(wrap(bearing-s.yaw))<.4){s.raised=true;s.aimed=false;note('Смена схемы: свой впереди. Оружие автоматически поднято до начала волны.');}s.ally={x:s.x+Math.sin(bearing)*7,y:1,z:s.z+Math.cos(bearing)*7,status:'active'};}else s.ally.status='gone';}s.history=[...s.history,...s.targets.map(t=>({...t}))].slice(-4);if(s.active)cue(s.targets[0]);}
  else {s.targets=[{x:-2.5,y:1.5,z:11,hits:0},{x:2.5,y:1.5,z:11,hits:0}];s.ally={x:s.stage===7?-5:0,y:1,z:7,status:s.stage===6?'gone':'active'};if(s.stage===7)s.targets=[{x:2,y:1.5,z:11,hits:0},{x:4,y:1.5,z:11,hits:0}];}
 if(!tutorial&&exercise==='front'){const lanes=[[-4.5,4.5,12],[-2.3,2.3,10],[-6.5,6.5,14]];const [left,right,z]=lanes[(s.wave-1)%3];s.targets=[{x:left,y:1.5,z,hits:0,side:'left'},{x:right,y:1.5,z,hits:0,side:'right'}];s.ally={x:0,y:1,z:7,status:s.wave%3===2?'gone':'active'};s.expectedSide='left';if(s.ally.status==='active'&&Math.abs(barrelAngle(s.ally))<.2){s.raised=true;s.aimed=false;}}
 }
 pair();
 function text(){const title=root.querySelector('#lessonTitle'),p=root.querySelector('#lessonText'); if(!tutorial){root.querySelector('#coach').hidden=true;return;} const row=lessons[s.stage];title.textContent=row[0];p.textContent=s.passed?(s.stage===8?'Вот теперь готов. Вперёд. Enter — в меню.':'Получилось. Enter — следующий шаг.'):row[1];root.querySelector('#nextLesson').hidden=!s.passed;root.querySelector('#nextLesson').textContent=s.stage===8?'Готово. В меню':'Дальше';}
 function pass(){if(!s.passed){s.passed=true;s.events=[];text();}}
 root.querySelector('#nextLesson').onclick=()=>{if(!s.passed)return;if(s.stage===8){dispose();onExit();return;}s.stage++;s.passed=false;s.x=0;s.z=0;s.yaw=-.4;s.pitch=0;s.raised=false;s.aimed=false;s.recoil=0;s.toggles=0;safeStart=null;s.events=[];s.ammo=30;s.reserve=90;s.history=[];s.wave=0;s.ally=null;if(s.stage===4)s.ammo=26;pair();text();};
 function dispose(){window.speechSynthesis?.cancel();s.done=true;abort.abort();cancelAnimationFrame(raf);if(document.pointerLockElement===c)document.exitPointerLock();}
 root.querySelector('#leaveRange').onclick=()=>{dispose();onExit();};
 const capture=root.querySelector('#capture');capture.onclick=()=>{s.active=true;last=performance.now();capture.hidden=true;c.focus();try{const req=c.requestPointerLock();req?.catch(()=>{s.active=true;});}catch{}};
 document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==c){s.active=false;s.aimed=false;keys.clear();capture.hidden=false;capture.textContent='Продолжить';}},opts);
 const keys=new Set();c.tabIndex=0;
 window.addEventListener('keydown',e=>{if(!s.active||s.done)return;if(['KeyW','KeyA','KeyS','KeyD','Space','KeyR'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(s.failure){if(e.code==='Enter'){s.failure=null;s.raised=true;s.aimed=false;s.passed=false;s.events=[];safeStart=null;s.targets.forEach(t=>{t.hits=0;t.fall=0;});s.ally.status='active';s.x=0;s.z=0;s.yaw=-.4;s.pitch=0;text();}return;}if(e.code==='Enter'&&tutorial&&s.passed){root.querySelector('#nextLesson').click();return;}
 if(e.code==='Space'){s.raised=!s.raised;if(s.raised)s.aimed=false;s.toggles++;if(tutorial&&(s.stage===6||s.stage===7)&&s.raised){s.unnecessary++;note('Лишний подъём на осмотренном свободном переносе. Повторите пару.');s.targets.forEach(t=>t.hits=0);}if(tutorial&&s.stage===1&&s.toggles>=2&&!s.raised)pass();if(tutorial&&s.stage===5){if(s.raised)safeStart=Math.abs(barrelAngle(s.ally))>.09?Math.sign(barrelAngle(s.ally)):null;else if(safeStart&&Math.sign(barrelAngle(s.ally))===-safeStart&&Math.abs(barrelAngle(s.ally))>.09)pass();}}
 if(e.code==='KeyR'&&!s.reload&&s.ammo<30&&s.reserve>0){s.reload=1.6;s.aimed=false;note('Извлекаю магазин…');cue({x:s.x,z:s.z+1});}
 },opts);
 window.addEventListener('keyup',e=>keys.delete(e.code),opts);
 window.addEventListener('blur',()=>{keys.clear();s.aimed=false;s.active=false;capture.hidden=false;},opts);
 c.addEventListener('mousemove',e=>{if(!s.active)return;const turn=e.movementX*.002*(s.aimed?.55:1),oldAngle=barrelAngle(s.ally);s.yaw+=turn;if(!s.raised&&s.ally.status==='active'&&!s.failure){const steps=Math.max(1,Math.ceil(Math.abs(turn)/.03));for(let i=0;i<=steps;i++){if(Math.abs(wrap(oldAngle-turn*i/steps))<.075){resign();break;}}}s.pitch=Math.max(-.6,Math.min(.6,s.pitch-e.movementY*.002*(s.aimed?.55:1)));},opts);
 c.addEventListener('contextmenu',e=>e.preventDefault(),opts);
 c.addEventListener('mousedown',e=>{if(!s.active)return;if(e.button===2&&!s.reload&&!s.raised)s.aimed=true;else if(e.button===0)shoot();},opts);
 window.addEventListener('mouseup',e=>{if(e.button===2)s.aimed=false;},opts);
 function angleTo(o){return wrap(Math.atan2(o.x-s.x,o.z-s.z)-s.yaw);}
 function project(x,y,z){let dx=x-s.x,dz=z-s.z;let side=dx*Math.cos(s.yaw)-dz*Math.sin(s.yaw),depth=dx*Math.sin(s.yaw)+dz*Math.cos(s.yaw);let up=y-1.65;const pitch=s.pitch+s.recoil;let yy=up*Math.cos(pitch)-depth*Math.sin(pitch),zz=up*Math.sin(pitch)+depth*Math.cos(pitch);if(zz<.12)return null;const f=c.height*(s.aimed?.95:.68);return {x:c.width/2+side*f/zz,y:c.height/2-yy*f/zz,k:f/zz,d:zz};}
 function rect(o,w,h){const p=project(o.x,o.y,o.z);return p&&{x:p.x-w*p.k/2,y:p.y-h*p.k/2,w:w*p.k,h:h*p.k};}
 function aimPoint(){return s.aimed?{x:c.width/2,y:c.height/2}:{x:c.width*.62,y:c.height*.94-290+s.recoil*700};}
 function hit(o,w,h){const r=rect(o,w,h),a=aimPoint();return r&&a.x>=r.x&&a.x<=r.x+r.w&&a.y>=r.y&&a.y<=r.y+r.h;}
 function barrelAngle(o){return wrap(angleTo(o)-Math.atan((aimPoint().x-c.width/2)/(c.height*(s.aimed?.95:.68))));}
 function failLesson(message){if(s.failure)return;say(message);s.failure=message;s.passed=false;safeStart=null;s.events=[message];root.querySelector('#lessonText').textContent=message+' Enter — повторить попытку. Карьера не затронута.';root.querySelector('#nextLesson').hidden=true;}
 function remaining(){return Math.max(0,officers-s.resign-s.killed);}
 function note(t){s.events=[t];}
 function resign(){if(s.ally.status!=='active')return;if(tutorial){failLesson('ОШИБКА: ствол наведён на своего. Сначала оружие вверх, потом поворот.');return;}s.ally.status='resigned';s.ally.depart=1.2;s.resign++;note('«Ствол убери! Я не могу так работать». Напарник увольняется.');say('Ствол убери! Я не могу так работать.');}
 function shoot(){if(s.failure||s.raised||s.reload||!s.ammo)return;s.ammo--;playShot();
 if(hit(s.ally,1.4,2.5)&&s.ally.status!=='killed'&&s.ally.status!=='gone'){
 if(tutorial){s.ally.status='killed';failLesson('ОШИБКА: попадание в напарника. Прекратить огонь. Повторим безопасный перенос.');}else{if(s.ally.status==='resigned')s.resign--;s.ally.status='killed';s.killed++;s.resign+=Math.min(2,remaining());note('Напарник погиб. Другие сотрудники отказываются работать с вами.');say('Прекратить огонь! Ты попал в своего!');}
 }else{for(const t of s.targets){if(t.hits<3&&hit(t,.9,1.3)){if(!tutorial&&exercise==='front'&&t.side!==s.expectedSide){s.orderErrors++;note('Нарушен порядок: сейчас '+(s.expectedSide==='left'?'ЛЕВАЯ':'ПРАВАЯ')+'. Попадание не засчитано.');break;}t.hits++;if(t.hits===3){t.fall=.35;s.destroyed++;if(exercise==='front'&&!tutorial)s.expectedSide=t.side==='left'?'right':'left';if(tutorial&&s.stage===2&&t===s.targets[0])pass();}if(tutorial&&s.stage===3&&s.aimed&&t===s.targets[1])pass();break;}}}
 s.recoil+=s.aimed?.012:.024;
 if(s.targets.every(t=>t.hits>=3)){if(tutorial&&(s.stage===6||s.stage===7))pass();else if(tutorial&&s.stage===8&&s.wave>=2)pass();else if(!tutorial||s.stage===8)s.intermission=1.2;}
 }
 function polygon(points,color){const pp=points.map(p=>project(...p));if(pp.some(p=>!p))return;ctx.fillStyle=color;ctx.beginPath();pp.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();ctx.strokeStyle='#526062';ctx.stroke();}
 function line(a,b){const p=project(...a),q=project(...b);if(!p||!q)return;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}
 function render(){c.width=root.clientWidth;c.height=root.clientHeight;ctx.fillStyle='#293337';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#171e20';ctx.fillRect(0,c.height*.5,c.width,c.height*.5);

 ctx.strokeStyle='#566163';for(let z=-16;z<=16;z+=2)line([-16,0,z],[16,0,z]);for(let x=-16;x<=16;x+=2)line([x,0,-16],[x,0,16]);for(let i=0;i<24;i++){const a=i*Math.PI/12,b=(i+1)*Math.PI/12;polygon([[16*Math.sin(a),0,16*Math.cos(a)],[16*Math.sin(b),0,16*Math.cos(b)],[16*Math.sin(b),4,16*Math.cos(b)],[16*Math.sin(a),4,16*Math.cos(a)]],i%2?'#394649':'#414b4c');}

 for(const t of s.targets){if(t.hits>=3&&!t.fall)continue;const r=rect({...t,y:t.y-(t.fall?1-t.fall/.35:0)},.9,t.fall?1.3*t.fall/.35:1.3);if(!r)continue;ctx.fillStyle='#c7b697';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle='#251f1a';ctx.lineWidth=3;ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.beginPath();ctx.ellipse(r.x+r.w/2,r.y+r.h/2,r.w*.32,r.h*.35,0,0,7);ctx.stroke();ctx.fillStyle='#eee';ctx.font='16px sans-serif';ctx.fillText(`${t.hits}/3`,r.x,r.y-10);}
 if(s.ally.status!=='gone'&&s.ally.status!=='killed'){const r=rect(s.ally,.7,1.7);if(r){ctx.fillStyle=s.ally.status==='resigned'?'#8a704c':'#436781';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle='#c3a58a';ctx.beginPath();ctx.arc(r.x+r.w/2,r.y-r.w*.2,r.w*.32,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.font='14px sans-serif';ctx.fillText('СВОЙ',r.x,r.y+r.h+18);}}
 // First-person weapon, fixed to the view with raised and ADS poses.
 ctx.save();ctx.translate(c.width*(s.raised?.76:s.aimed?.5:.62),s.raised?c.height*.7:s.aimed?c.height/2+210:c.height*.94+s.recoil*700);if(s.reload)ctx.translate(0,-155);ctx.rotate(s.reload?.28:0);ctx.scale(s.raised?1.3:1,s.raised?1.55:1);ctx.fillStyle='#171b1d';ctx.strokeStyle='#89908c';ctx.lineWidth=3;ctx.fillRect(-36,-145,72,225);ctx.strokeRect(-36,-145,72,225);ctx.fillStyle='#384046';ctx.fillRect(-23,-210,46,130);ctx.fillStyle='#101416';ctx.fillRect(-9,-290,18,110);ctx.strokeRect(-18,-230,36,35);ctx.fillStyle='#4c5044';ctx.fillRect(-60,5,40,120);ctx.fillRect(30,40,45,110);if(s.reload){const f=1-s.reload/1.6;ctx.fillStyle='#87908d';ctx.fillRect(-20,40+Math.sin(f*Math.PI)*125,40,85);}ctx.restore();if(s.aimed&&!s.raised&&!s.reload){ctx.strokeStyle='#151b1e';ctx.lineWidth=8;ctx.strokeRect(c.width/2-35,c.height/2-35,70,70);ctx.fillStyle='#ef543d';ctx.fillRect(c.width/2-2,c.height/2-2,4,4);}
 if(s.aimed&&!s.raised&&!s.reload){ctx.strokeStyle=s.raised?'#e0bb67':'#fff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(c.width/2-8,c.height/2);ctx.lineTo(c.width/2+8,c.height/2);ctx.moveTo(c.width/2,c.height/2-8);ctx.lineTo(c.width/2,c.height/2+8);ctx.stroke();}if(s.failure){ctx.fillStyle='#720d16e8';ctx.fillRect(0,c.height*.54,c.width,90);ctx.fillStyle='#fff';ctx.font='20px sans-serif';ctx.fillText('СТОП — ОШИБКА БЕЗОПАСНОСТИ. Enter: повторить',30,c.height*.54+50);}
 root.querySelector('#stats').textContent=tutorial?'УЧЕБНАЯ ПЛОЩАДКА · без штрафов':`${(90-s.elapsed).toFixed(1)} с · ${exercise==='front'?'Вторая смена · Сейчас '+(s.expectedSide==='left'?'ЛЕВАЯ':'ПРАВАЯ'):'Первая смена'} · Мишени ${s.destroyed} · Сотрудники ${remaining()}`;
 if(s.reload){ctx.fillStyle='#080d10';ctx.fillRect(c.width/2-170,c.height*.68-27,340,64);ctx.strokeStyle='#adb8b7';ctx.lineWidth=1;ctx.strokeRect(c.width/2-160,c.height*.72,320,30);ctx.fillStyle='#fff';ctx.font='17px sans-serif';ctx.fillText('ПЕРЕЗАРЯДКА · '+Math.ceil(s.reload*10)/10+' с',c.width/2-150,c.height*.68);ctx.fillStyle='#e0bb67';ctx.fillRect(c.width/2-155,c.height*.72+5,310*(1-s.reload/1.6),20);}
 root.querySelector('#gunStatus').textContent=`${s.reload?(s.reload>.8?'ПЕРЕЗАРЯДКА: извлекаю магазин':'ПЕРЕЗАРЯДКА: устанавливаю магазин'):s.raised?'СТВОЛ ВВЕРХ — безопасно':'ГОТОВО К СТРЕЛЬБЕ'} · В оружии: ${s.ammo} / 30 · В запасе: ${s.reserve}${!s.ammo?' · МАГАЗИН ПУСТ — R':!s.reserve?' · ЗАПАСА НЕТ':''}${s.events.length?' · '+s.events[0]:''}`;
 }
 function loop(now){if(s.done)return;const dt=Math.min(.05,(now-last)/1000);last=now;
 if(s.active){for(const t of s.targets)if(t.fall)t.fall=Math.max(0,t.fall-dt);if(tutorial&&!s.ammo&&!s.reserve){s.ammo=30;s.reserve=90;note('Учебный боезапас пополнен. Повторите действие.');}if(s.intermission){s.intermission=Math.max(0,s.intermission-dt);if(!s.intermission)pair();}if(!tutorial)s.elapsed+=dt;const speed=dt*2;let forward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),side=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);s.x=Math.max(-5,Math.min(5,s.x+(Math.sin(s.yaw)*forward+Math.cos(s.yaw)*side)*speed));s.z=Math.max(-2,Math.min(4,s.z+(Math.cos(s.yaw)*forward-Math.sin(s.yaw)*side)*speed));for(const k of ['KeyW','KeyS','KeyA','KeyD'])if(keys.has(k)&&dt>0){s.moveDurations ||= {};s.moveDurations[k]=(s.moveDurations[k]||0)+dt;if(s.moveDurations[k]>=.12)s.moved.add(k);}if(tutorial&&s.stage===0&&s.moved.size===4)pass();
 s.recoil*=Math.exp(-dt*9);if(s.reload){s.reload=Math.max(0,s.reload-dt);if(!s.reload){const n=Math.min(30-s.ammo,s.reserve);s.ammo+=n;s.reserve-=n;note('Магазин установлен. ГОТОВО');cue({x:s.x,z:s.z+1});if(tutorial&&s.stage===4)pass();}}
 if(!s.raised&&s.ally.status==='active'&&!s.failure&&Math.abs(barrelAngle(s.ally))<.075)resign();
 if(s.ally.status==='resigned'){s.ally.depart-=dt;if(s.ally.depart<=0)s.ally.status='gone';}
 if(!tutorial&&(s.elapsed>=90||(!s.ammo&&!s.reserve)||remaining()===0)){const reason=remaining()===0?'no_officers':!s.ammo&&!s.reserve?'ammo_depleted':'time_limit';dispose();onFinish({destroyed:s.destroyed,resign:s.resign,killed:s.killed,duration:Math.min(90,s.elapsed),orderErrors:s.orderErrors,reason});return;}}
 render();raf=requestAnimationFrame(loop);
 }
 text();raf=requestAnimationFrame(loop);return {dispose,state:s};
}
